USE unxsvz;

/*
DROP TABLE IF EXISTS tIPType;
CREATE TABLE IF NOT EXISTS tIPType (
        uIPType INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
        cLabel VARCHAR(32) NOT NULL,
	uOwner INT UNSIGNED NOT NULL DEFAULT 0,INDEX (uOwner),
	uCreatedBy INT UNSIGNED NOT NULL DEFAULT 0,
	uCreatedDate INT UNSIGNED NOT NULL DEFAULT 0,
	uModBy INT UNSIGNED NOT NULL DEFAULT 0,
	uModDate INT UNSIGNED NOT NULL DEFAULT 0,
        cComment TEXT NOT NULL
        );
*/
TRUNCATE tIPType;
LOAD DATA INFILE '/home/unxs/unxsVZ/agents/snort/sql/tIPType.csv' 
        INTO TABLE tIPType
        FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
        LINES TERMINATED BY '\n' STARTING BY '' 
        ;
