// svn ID removed
// English: USA
// Navigation bar buttons and results

#define LANG_NB_LIST "List"
#define LANG_NB_MODIFY "Modify"
#define LANG_NB_CONFIRMMOD "Confirm Modify"
#define LANG_NB_NEW "New"
#define LANG_NB_DELETE "Delete"
#define LANG_NB_CONFIRMNEW "Create New Record"
#define LANG_NBB_CONFIRMNEW "<input class=lrevButton title='Double check!' type=submit name=gcCommand value=\"Create New Record\">"
#define LANG_NB_CONFIRMDEL "Confirm Delete"
#define LANG_NBB_CONFIRMDEL "<input class=lwarnButton title='No undo available!' type=submit name=gcCommand value=\"Confirm Delete\">"
#define LANG_NBB_CONFIRMMOD "<input class=lalertButton title='Double check!' type=submit name=gcCommand value=\"Confirm Modify\">"


#define LANG_NBR_FOUND " Found"
#define LANG_NBR_MODIFIED " Modified"
#define LANG_NBR_NEW " New"
#define LANG_NBR_NORECS " No records found"
#define LANG_NBRF_SHOWING " (Showing %lu of %d)"

#define LANG_NBR_RECEXISTS "<blink>Record already exists"
#define LANG_NBR_NEWRECADDED "New record %u added"
#define LANG_NBR_RECDELETED "Record Deleted"
#define LANG_NBR_RECNOTDELETED "Record Not Deleted"
#define LANG_NBR_RECNOTEXIST "<blink>Record does not exist"
#define LANG_NBR_MULTRECS "<blink>Multiple rows!"
#define LANG_NBR_EXTMOD "<blink>This record was just modified by another user!"
#define LANG_NBRF_REC_MODIFIED "record %s modified"

#define LANG_NBB_SKIPFIRST "<input style='width:20px;' title=\"Skip to first record\" type=submit name=gcFind value=\"<<\" >"
#define LANG_NBB_SKIPBACK "<input style='width:20px;' title=\"Go back one record\" type=submit name=gcFind value=\"< \" >"
#define LANG_NBB_SKIPNEXT "<input style='width:20px;' title=\"Advance to next record\" type=submit name=gcFind value=\" >\" >"
#define LANG_NBB_SKIPLAST "<input style='width:20px;' title=\"Skip to last record\" type=submit name=gcFind value=\">>\" >\n"

//Modified for local .h use
#define LANG_NBB_NEWREV "<input class=revButton title=\"Create new record\" type=submit name=gcCommand value=New>"
#define LANG_NBB_NEW "<input  title=\"Create new record\" type=submit name=gcCommand value=New>"
#define LANG_NBB_DELETE "<input class=warnButton title=\"Delete current record\" type=submit name=gcCommand value=Delete>"
#define LANG_NBB_MODIFY "<input class=alertButton title=\"Modify current record\" type=submit name=gcCommand value=Modify>"

#define LANG_NBB_LIST "<input title=\"Paginated listing of all records\" type=submit name=gcFind value=List>"
#define LANG_NBB_SEARCH "<input class=revButton title=\"Find record with parameters set below\" type=submit name=gcFind value=Search>"

#define LANG_PAGEMACHINE_HINT "No matching records found.<br>"
#define LANG_PAGEMACHINE_SHOWING "Page %d/%d (Records %d-%d of %d)\n"
#define LANG_PAGEMACHINE_SEARCH "<input type=submit name=gcFind value=Search >"
#define LANG_PAGEMACHINE_SEARCHBUTTON "Search"


//tClient
#define LANG_FL_tClient_uClient "uClient"
#define LANG_FT_tClient_uClient "Primary Key"
#define LANG_FL_tClient_cLabel "cLabel"
#define LANG_FT_tClient_cLabel "Short label"
#define LANG_FL_tClient_cResellerCode "cResellerCode"
#define LANG_FT_tClient_cResellerCode "Reseller code"
#define LANG_FL_tClient_cCompanyName "cCompanyName"
#define LANG_FT_tClient_cCompanyName "Company name"
#define LANG_FL_tClient_cCompanyRegistration "cCompanyRegistration"
#define LANG_FT_tClient_cCompanyRegistration "Company registration"
#define LANG_FL_tClient_cVAT "cVAT"
#define LANG_FT_tClient_cVAT "VAT number"
#define LANG_FL_tClient_cFirstName "cFirstName"
#define LANG_FT_tClient_cFirstName "First Name"
#define LANG_FL_tClient_cLastName "cLastName"
#define LANG_FT_tClient_cLastName "Last Name"
#define LANG_FL_tClient_cIDNumber "cIDNumber"
#define LANG_FT_tClient_cIDNumber "ID Number"
#define LANG_FL_tClient_cEmail "cEmail"
#define LANG_FT_tClient_cEmail "eMail"
#define LANG_FL_tClient_cAddr1 "cAddr1"
#define LANG_FT_tClient_cAddr1 "Street mailing address"
#define LANG_FL_tClient_cAddr2 "cAddr2"
#define LANG_FT_tClient_cAddr2 "Street mailing address line 2"
#define LANG_FL_tClient_cAddr3 "cAddr3"
#define LANG_FT_tClient_cAddr3 "Street mailing address line 3"
#define LANG_FL_tClient_cCity "cCity"
#define LANG_FT_tClient_cCity "City"
#define LANG_FL_tClient_cState "cState"
#define LANG_FT_tClient_cState "State, Province or Locality"
#define LANG_FL_tClient_cZip "cZip"
#define LANG_FT_tClient_cZip "Postal or Zip code"
#define LANG_FL_tClient_cCountry "cCountry"
#define LANG_FT_tClient_cCountry "Country"
#define LANG_FL_tClient_uPayment "uPayment"
#define LANG_FT_tClient_uPayment "Preferred payment method"
#define LANG_FL_tClient_cBankName "cBankName"
#define LANG_FT_tClient_cBankName "Bank name"
#define LANG_FL_tClient_cBranchName "cBranchName"
#define LANG_FT_tClient_cBranchName "Branch name"
#define LANG_FL_tClient_cBranchCode "cBranchCode"
#define LANG_FT_tClient_cBranchCode "Branch code"
#define LANG_FL_tClient_cAccountHolder "cAccountHolder"
#define LANG_FT_tClient_cAccountHolder "Name of the account holder"
#define LANG_FL_tClient_cAccountNumber "cAccountNumber"
#define LANG_FT_tClient_cAccountNumber "Account number"
#define LANG_FL_tClient_uAccountType "uAccountType"
#define LANG_FT_tClient_uAccountType "Account type"
#define LANG_FL_tClient_cCardType "cCardType"
#define LANG_FT_tClient_cCardType "Credit Card Type"
#define LANG_FL_tClient_cCardNumber "cCardNumber"
#define LANG_FT_tClient_cCardNumber "Credit Card Number"
#define LANG_FL_tClient_uExpMonth "uExpMonth"
#define LANG_FT_tClient_uExpMonth "Credit card expiration month"
#define LANG_FL_tClient_uExpYear "uExpYear"
#define LANG_FT_tClient_uExpYear "Credit card expiration year"
#define LANG_FL_tClient_cCardName "cCardName"
#define LANG_FT_tClient_cCardName "Name as appears on credit card"
#define LANG_FL_tClient_cACHDebits "cACHDebits"
#define LANG_FT_tClient_cACHDebits "ABA routing number + account number"
#define LANG_FL_tClient_cShipName "cShipName"
#define LANG_FT_tClient_cShipName "Shipping address name"
#define LANG_FL_tClient_cShipAddr1 "cShipAddr1"
#define LANG_FT_tClient_cShipAddr1 "Shipping street address"
#define LANG_FL_tClient_cShipAddr2 "cShipAddr2"
#define LANG_FT_tClient_cShipAddr2 "Shipping street address line 2"
#define LANG_FL_tClient_cShipAddr3 "cShipAddr3"
#define LANG_FT_tClient_cShipAddr3 "Shipping street address line 3"
#define LANG_FL_tClient_cShipCity "cShipCity"
#define LANG_FT_tClient_cShipCity "Shipping city"
#define LANG_FL_tClient_cShipState "cShipState"
#define LANG_FT_tClient_cShipState "Shipping state or province"
#define LANG_FL_tClient_cShipZip "cShipZip"
#define LANG_FT_tClient_cShipZip "Shipping zip or postal code"
#define LANG_FL_tClient_cShipCountry "cShipCountry"
#define LANG_FT_tClient_cShipCountry "Shipping country"
#define LANG_FL_tClient_cTelephone "cTelephone"
#define LANG_FT_tClient_cTelephone "Customer Telephone"
#define LANG_FL_tClient_cMobile "cMobile"
#define LANG_FT_tClient_cMobile "Customer mobile phone number"
#define LANG_FL_tClient_cFax "cFax"
#define LANG_FT_tClient_cFax "Customer Fax"
#define LANG_FL_tClient_cPasswd "cPasswd"
#define LANG_FT_tClient_cPasswd "crypt() encrypted password for login systems"
#define LANG_FL_tClient_mBalance "mBalance"
#define LANG_FT_tClient_mBalance "Customer balance"
#define LANG_FL_tClient_mTotal "mTotal"
#define LANG_FT_tClient_mTotal "mTotal"
#define LANG_FL_tClient_uReseller "uReseller"
#define LANG_FL_tClient_cInfo "cInfo"
#define LANG_FT_tClient_cInfo "Unformatted info/address etc."
#define LANG_FL_tClient_cLanguage "cLanguage"
#define LANG_FT_tClient_cLanguage "Customer language for invoice rendering"
#define LANG_FT_tClient_uReseller "tClient row id of the reseller for this customer"
#define LANG_FL_tClient_uOwner "uOwner"
#define LANG_FT_tClient_uOwner "Record owner"
#define LANG_FL_tClient_uCreatedBy "uCreatedBy"
#define LANG_FT_tClient_uCreatedBy "uClient for last insert"
#define LANG_FL_tClient_uCreatedDate "uCreatedDate"
#define LANG_FT_tClient_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tClient_uModBy "uModBy"
#define LANG_FT_tClient_uModBy "uClient for last update"
#define LANG_FL_tClient_uModDate "uModDate"
//tProduct
#define LANG_FL_tProduct_uProduct "uProduct"
#define LANG_FT_tProduct_uProduct "Primary Key"
#define LANG_FL_tProduct_cLabel "cLabel"
#define LANG_FT_tProduct_cLabel "Short label"
#define LANG_FL_tProduct_uAvailable "uAvailable"
#define LANG_FT_tProduct_uAvailable "Available for use"
#define LANG_FL_tProduct_uPeriod "uPeriod"
#define LANG_FT_tProduct_uPeriod "One-time or recurring billing period"

#define LANG_FL_tProduct_mPrice "mPrice"
#define LANG_FT_tProduct_mPrice "Billing price per period"

#define LANG_FL_tProduct_mCost "mCost"
#define LANG_FT_tProduct_mCost "Cost per period"

#define LANG_FL_tProduct_mSetupFee "mSetupFee"
#define LANG_FT_tProduct_mSetupFee "One time setup fee"

#define LANG_FL_tProduct_mReleaseFee "mReleaseFee"
#define LANG_FT_tProduct_mReleaseFee "One time release fee. For release of a hold etc."

#define LANG_FL_tProduct_cComment "cComment"
#define LANG_FT_tProduct_cComment "Product description comments"
#define LANG_FL_tProduct_uProductType "uProductType"
#define LANG_FT_tProduct_uProductType "Main service area for this product"
#define LANG_FL_tProduct_cTitle "cTitle"
#define LANG_FT_tProduct_cTitle "html title for select in ism3"
#define LANG_FL_tProduct_uOwner "uOwner"
#define LANG_FT_tProduct_uOwner "Record owner"
#define LANG_FL_tProduct_uCreatedBy "uCreatedBy"
#define LANG_FT_tProduct_uCreatedBy "uClient for last insert"
#define LANG_FL_tProduct_uCreatedDate "uCreatedDate"
#define LANG_FT_tProduct_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tProduct_uModBy "uModBy"
#define LANG_FT_tProduct_uModBy "uClient for last update"
#define LANG_FL_tProduct_uModDate "uModDate"
#define LANG_FT_tProduct_uModDate "Unix seconds date last update"
//tService
#define LANG_FL_tService_uService "uService"
#define LANG_FT_tService_uService "Primary Key"
#define LANG_FL_tService_cLabel "cLabel"
#define LANG_FT_tService_cLabel "Short label"
#define LANG_FL_tService_uAvailable "uAvailable"
#define LANG_FT_tService_uAvailable "Available for use"
#define LANG_FL_tService_cServer "cServer"
#define LANG_FT_tService_cServer "Server domain name or IP"
#define LANG_FL_tService_cJobName "cJobName"
#define LANG_FT_tService_cJobName "Job name used by target application"
#define LANG_FL_tService_cComment "cComment"
#define LANG_FT_tService_cComment "Customer use and other comments"
#define LANG_FL_tService_uOwner "uOwner"
#define LANG_FT_tService_uOwner "Record owner"
#define LANG_FL_tService_uCreatedBy "uCreatedBy"
#define LANG_FT_tService_uCreatedBy "uClient for last insert"
#define LANG_FL_tService_uCreatedDate "uCreatedDate"
#define LANG_FT_tService_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tService_uModBy "uModBy"
#define LANG_FT_tService_uModBy "uClient for last update"
#define LANG_FL_tService_uModDate "uModDate"
#define LANG_FT_tService_uModDate "Unix seconds date last update"
//tInstance
#define LANG_FL_tInstance_uInstance "uInstance"
#define LANG_FT_tInstance_uInstance "Primary key"
#define LANG_FL_tInstance_uClient "uClient"
#define LANG_FT_tInstance_uClient "Client index"
#define LANG_FL_tInstance_uProduct "uProduct"
#define LANG_FT_tInstance_uProduct "Product"
#define LANG_FL_tInstance_cLabel "cLabel"
#define LANG_FT_tInstance_cLabel "Instance label"
#define LANG_FL_tInstance_uBilled "uBilled"
#define LANG_FT_tInstance_uBilled "Last unixtime billed"

#define LANG_FL_tInstance_uLastPaid "uLastPaid"
#define LANG_FT_tInstance_uLastPaid "Last unixtime paid"

#define LANG_FL_tInstance_uPayment "uPayment"
#define LANG_FT_tInstance_uPayment "Invoice and charge with this payment type"

#define LANG_FL_tInstance_uShipping "uShipping"
#define LANG_FT_tInstance_uShipping "Invoice with this shipping type. Usually none."

#define LANG_FL_tInstance_uStatus "uStatus"
#define LANG_FT_tInstance_uStatus "Product status for this client instance"
#define LANG_FL_tInstance_uOwner "uOwner"
#define LANG_FT_tInstance_uOwner "Record owner"
#define LANG_FL_tInstance_uCreatedBy "uCreatedBy"
#define LANG_FT_tInstance_uCreatedBy "uClient for last insert"
#define LANG_FL_tInstance_uCreatedDate "uCreatedDate"
#define LANG_FT_tInstance_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tInstance_uModBy "uModBy"
#define LANG_FT_tInstance_uModBy "uClient for last update"
#define LANG_FL_tInstance_uModDate "uModDate"
#define LANG_FT_tInstance_uModDate "Unix seconds date last update"
//tJob
#define LANG_FL_tJob_uJob "uJob"
#define LANG_FT_tJob_uJob "Primary Key"
#define LANG_FL_tJob_uJobGroup "uJobGroup"
#define LANG_FT_tJob_uJobGroup "Same as first uJob for related instance service jobs"
#define LANG_FL_tJob_cLabel "cLabel"
#define LANG_FT_tJob_cLabel "Short label"
#define LANG_FL_tJob_cServer "cServer"
#define LANG_FT_tJob_cServer "Server name ip or any server"
#define LANG_FL_tJob_cJobName "cJobName"
#define LANG_FT_tJob_cJobName "Subsystem.Function style job name"
#define LANG_FL_tJob_uJobClient "uJobClient"
#define LANG_FT_tJob_uJobClient "Owner of resources created/mod"
#define LANG_FL_tJob_uInstance "uInstance"
#define LANG_FT_tJob_uInstance "Job belongs to this product instance"
#define LANG_FL_tJob_cJobData "cJobData"
#define LANG_FT_tJob_cJobData "Remote subsystem server function arguments"
#define LANG_FL_tJob_uJobDate "uJobDate"
#define LANG_FT_tJob_uJobDate "Unix seconds for job to start to be considered"
#define LANG_FL_tJob_uJobStatus "uJobStatus"
#define LANG_FT_tJob_uJobStatus "Waiting, being processed, done, error"
#define LANG_FL_tJob_cRemoteMsg "cRemoteMsg"
#define LANG_FT_tJob_cRemoteMsg "Remote subsytem error message"
#define LANG_FL_tJob_uOwner "uOwner"
#define LANG_FT_tJob_uOwner "Record owner"
#define LANG_FL_tJob_uCreatedBy "uCreatedBy"
#define LANG_FT_tJob_uCreatedBy "uClient for last insert"
#define LANG_FL_tJob_uCreatedDate "uCreatedDate"
#define LANG_FT_tJob_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJob_uModBy "uModBy"
#define LANG_FT_tJob_uModBy "uClient for last update"
#define LANG_FL_tJob_uModDate "uModDate"
#define LANG_FT_tJob_uModDate "Unix seconds date last update"
//tClientConfig
#define LANG_FL_tClientConfig_uConfig "uConfig"
#define LANG_FT_tClientConfig_uConfig "Primary Key"
#define LANG_FL_tClientConfig_uGroup "uGroup"
#define LANG_FT_tClientConfig_uGroup "Product configuration instance"
#define LANG_FL_tClientConfig_uService "uService"
#define LANG_FT_tClientConfig_uService "Service this parameter belongs to."
#define LANG_FL_tClientConfig_uParameter "uParameter"
#define LANG_FT_tClientConfig_uParameter "Parameter name pointer"
#define LANG_FL_tClientConfig_cValue "cValue"
#define LANG_FT_tClientConfig_cValue "Parameter value"
#define LANG_FL_tClientConfig_uOwner "uOwner"
#define LANG_FT_tClientConfig_uOwner "Record owner"
#define LANG_FL_tClientConfig_uCreatedBy "uCreatedBy"
#define LANG_FT_tClientConfig_uCreatedBy "uClient for last insert"
#define LANG_FL_tClientConfig_uCreatedDate "uCreatedDate"
#define LANG_FT_tClientConfig_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tClientConfig_uModBy "uModBy"
#define LANG_FT_tClientConfig_uModBy "uClient for last update"
#define LANG_FL_tClientConfig_uModDate "uModDate"
#define LANG_FT_tClientConfig_uModDate "Unix seconds date last update"
//tConfig
#define LANG_FL_tConfig_uConfig "uConfig"
#define LANG_FT_tConfig_uConfig "Primary Key"
#define LANG_FL_tConfig_uGroup "uGroup"
#define LANG_FT_tConfig_uGroup "Service configuration instance group index"
#define LANG_FL_tConfig_uParameter "uParameter"
#define LANG_FT_tConfig_uParameter "Parameter name pointer"
#define LANG_FL_tConfig_cValue "cValue"
#define LANG_FT_tConfig_cValue "Parameter value"
#define LANG_FL_tConfig_uOwner "uOwner"
#define LANG_FT_tConfig_uOwner "Record owner"
#define LANG_FL_tConfig_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfig_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfig_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfig_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfig_uModBy "uModBy"
#define LANG_FT_tConfig_uModBy "uClient for last update"
#define LANG_FL_tConfig_uModDate "uModDate"
#define LANG_FT_tConfig_uModDate "Unix seconds date last update"
//tParameter
#define LANG_FL_tParameter_uParameter "uParameter"
#define LANG_FT_tParameter_uParameter "Primary Key"
#define LANG_FL_tParameter_cParameter "cParameter"
#define LANG_FT_tParameter_cParameter "Parameter name"
#define LANG_FL_tParameter_uParamType "uParamType"
#define LANG_FT_tParameter_uParamType "Parameter type"
#define LANG_FL_tParameter_cRange "cRange"
#define LANG_FT_tParameter_cRange "Parameter range"
#define LANG_FL_tParameter_uUnique "uUnique"
#define LANG_FT_tParameter_uUnique "Enforce unique value in tClientConfig"
#define LANG_FL_tParameter_cExtVerify "cExtVerify"
#define LANG_FT_tParameter_cExtVerify "External synchronous database verification server and query"
#define LANG_FL_tParameter_uModPostDeploy "uModPostDeploy"
#define LANG_FT_tParameter_uModPostDeploy "Allow after deployment modification"
#define LANG_FL_tParameter_uAllowMod "uAllowMod"
#define LANG_FT_tParameter_uAllowMod "Allow user modification of parameter value"
#define LANG_FL_tParameter_uISMOrder "uISMOrder"
#define LANG_FT_tParameter_uISMOrder "The display order for the field"
#define LANG_FL_tParameter_uISMHide "uISMHide"
#define LANG_FT_tParameter_uISMHide "Hide on ism3 edit product form"
#define LANG_FL_tParameter_cISMName "cISMName"
#define LANG_FT_tParameter_cISMName "ism3 edit product parameter field name shown on form"
#define LANG_FL_tParameter_cISMHelp "cISMHelp"
#define LANG_FT_tParameter_cISMHelp "ism3 edit product parameter field help (title)"
#define LANG_FL_tParameter_uProductType "uProductType"
#define LANG_FT_tParameter_uProductType "Main product-service type"
#define LANG_FL_tParameter_cExtQuery "cExtQuery"
#define LANG_FT_tParameter_cExtQuery "External query for extselect parameters"
#define LANG_FL_tParameter_uOwner "uOwner"
#define LANG_FT_tParameter_uOwner "Record owner"
#define LANG_FL_tParameter_uCreatedBy "uCreatedBy"
#define LANG_FT_tParameter_uCreatedBy "uClient for last insert"
#define LANG_FL_tParameter_uCreatedDate "uCreatedDate"
#define LANG_FT_tParameter_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tParameter_uModBy "uModBy"
#define LANG_FT_tParameter_uModBy "uClient for last update"
#define LANG_FL_tParameter_uModDate "uModDate"
#define LANG_FT_tParameter_uModDate "Unix seconds date last update"
//tParamType
#define LANG_FL_tParamType_uParamType "uParamType"
#define LANG_FT_tParamType_uParamType "Primary Key"
#define LANG_FL_tParamType_cLabel "cLabel"
#define LANG_FT_tParamType_cLabel "Short label"
#define LANG_FL_tParamType_uOwner "uOwner"
#define LANG_FT_tParamType_uOwner "Record owner"
#define LANG_FL_tParamType_uCreatedBy "uCreatedBy"
#define LANG_FT_tParamType_uCreatedBy "uClient for last insert"
#define LANG_FL_tParamType_uCreatedDate "uCreatedDate"
#define LANG_FT_tParamType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tParamType_uModBy "uModBy"
#define LANG_FT_tParamType_uModBy "uClient for last update"
#define LANG_FL_tParamType_uModDate "uModDate"
#define LANG_FT_tParamType_uModDate "Unix seconds date last update"
//tPeriod
#define LANG_FL_tPeriod_uPeriod "uPeriod"
#define LANG_FT_tPeriod_uPeriod "Primary Key"
#define LANG_FL_tPeriod_cLabel "cLabel"
#define LANG_FT_tPeriod_cLabel "Short label"
#define LANG_FL_tPeriod_uOwner "uOwner"
#define LANG_FT_tPeriod_uOwner "Record owner"
#define LANG_FL_tPeriod_uCreatedBy "uCreatedBy"
#define LANG_FT_tPeriod_uCreatedBy "uClient for last insert"
#define LANG_FL_tPeriod_uCreatedDate "uCreatedDate"
#define LANG_FT_tPeriod_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tPeriod_uModBy "uModBy"
#define LANG_FT_tPeriod_uModBy "uClient for last update"
#define LANG_FL_tPeriod_uModDate "uModDate"
#define LANG_FT_tPeriod_uModDate "Unix seconds date last update"
//tStatus
#define LANG_FL_tStatus_uStatus "uStatus"
#define LANG_FT_tStatus_uStatus "Primary Key"
#define LANG_FL_tStatus_cLabel "cLabel"
#define LANG_FT_tStatus_cLabel "Short label"
#define LANG_FL_tStatus_cComment "cComment"
#define LANG_FT_tStatus_cComment "Comments for developers"
#define LANG_FL_tStatus_uOwner "uOwner"
#define LANG_FT_tStatus_uOwner "Record owner"
#define LANG_FL_tStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tStatus_uModBy "uModBy"
#define LANG_FT_tStatus_uModBy "uClient for last update"
#define LANG_FL_tStatus_uModDate "uModDate"
#define LANG_FT_tStatus_uModDate "Unix seconds date last update"
//tAuthorize
#define LANG_FL_tAuthorize_uAuthorize "uAuthorize"
#define LANG_FT_tAuthorize_uAuthorize "Primary Key"
#define LANG_FL_tAuthorize_cLabel "cLabel"
#define LANG_FT_tAuthorize_cLabel "Short label"
#define LANG_FL_tAuthorize_cIpMask "cIpMask"
#define LANG_FT_tAuthorize_cIpMask "Allow user from this IP"
#define LANG_FL_tAuthorize_uPerm "uPerm"
#define LANG_FT_tAuthorize_uPerm "User permission level"
#define LANG_FL_tAuthorize_uCertClient "uCertClient"
#define LANG_FT_tAuthorize_uCertClient "User uClient"
#define LANG_FL_tAuthorize_cPasswd "cPasswd"
#define LANG_FT_tAuthorize_cPasswd "Unix crypt() password"
#define LANG_FL_tAuthorize_cClrPasswd "cClrPasswd"
#define LANG_FT_tAuthorize_cClrPasswd "Optionally used non encrypted login password"
#define LANG_FL_tAuthorize_uOwner "uOwner"
#define LANG_FT_tAuthorize_uOwner "Record owner"
#define LANG_FL_tAuthorize_uCreatedBy "uCreatedBy"
#define LANG_FT_tAuthorize_uCreatedBy "uClient for last insert"
#define LANG_FL_tAuthorize_uCreatedDate "uCreatedDate"
#define LANG_FT_tAuthorize_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tAuthorize_uModBy "uModBy"
#define LANG_FT_tAuthorize_uModBy "uClient for last update"
#define LANG_FL_tAuthorize_uModDate "uModDate"
#define LANG_FT_tAuthorize_uModDate "Unix seconds date last update"
//tServiceGlue
#define LANG_FL_tServiceGlue_uServiceGlue "uServiceGlue"
#define LANG_FT_tServiceGlue_uServiceGlue "Primary Key"
#define LANG_FL_tServiceGlue_uServiceGroup "uServiceGroup"
#define LANG_FT_tServiceGlue_uServiceGroup "Product with one or more associated services"
#define LANG_FL_tServiceGlue_uService "uService"
#define LANG_FT_tServiceGlue_uService "Service grouped by product"
//tInvoice
#define LANG_FL_tInvoice_uInvoice "uInvoice"
#define LANG_FT_tInvoice_uInvoice "Primary Key"
#define LANG_FL_tInvoice_uShipping "uShipping"
#define LANG_FT_tInvoice_uShipping "Shipping method for all products on invoice"
#define LANG_FL_tInvoice_uPayment "uPayment"
#define LANG_FT_tInvoice_uPayment "Payment method for all products on invoice"
#define LANG_FL_tInvoice_uInvoiceStatus "uInvoiceStatus"
#define LANG_FT_tInvoice_uInvoiceStatus "Invoice status"
#define LANG_FL_tInvoice_uQueueStatus "uQueueStatus"
#define LANG_FT_tInvoice_uQueueStatus "unxsISP tJob queue status"
#define LANG_FL_tInvoice_uClient "uClient"
#define LANG_FT_tInvoice_uClient "Client ID"
#define LANG_FL_tInvoice_mTotal "mTotal"
#define LANG_FT_tInvoice_mTotal "Invoice total from non credit tInvoiceItems"
#define LANG_FL_tInvoice_mPaid "mPaid"
#define LANG_FT_tInvoice_mPaid "Invoice total from all tInvoiceItems"
#define LANG_FL_tInvoice_mSH "mSH"
#define LANG_FT_tInvoice_mSH "Shipping and handling total"
#define LANG_FL_tInvoice_mTax "mTax"
#define LANG_FT_tInvoice_mTax "Total tax"
#define LANG_FL_tInvoice_cComments "cComments"
#define LANG_FT_tInvoice_cComments "Customer or our comments about order"
#define LANG_FL_tInvoice_cAuthCode "cAuthCode"
#define LANG_FT_tInvoice_cAuthCode "Credit card processor or other authorization code"
#define LANG_FL_tInvoice_cPnRef "cPnRef"
#define LANG_FT_tInvoice_cPnRef "Online payment processor tansaction reference"
#define LANG_FL_tInvoice_uAvsAddr "uAvsAddr"
#define LANG_FT_tInvoice_uAvsAddr "AVS address verified"
#define LANG_FL_tInvoice_uAvsZip "uAvsZip"
#define LANG_FT_tInvoice_uAvsZip "AVS zipcode verified"
#define LANG_FL_tInvoice_uResultCode "uResultCode"
#define LANG_FT_tInvoice_uResultCode "Payment processor result code"
#define LANG_FL_tInvoice_cFirstName "cFirstName"
#define LANG_FT_tInvoice_cFirstName "First Name"
#define LANG_FL_tInvoice_cLastName "cLastName"
#define LANG_FT_tInvoice_cLastName "Last Name"
#define LANG_FL_tInvoice_cEmail "cEmail"
#define LANG_FT_tInvoice_cEmail "eMail"
#define LANG_FL_tInvoice_cAddr1 "cAddr1"
#define LANG_FT_tInvoice_cAddr1 "Street mailing address"
#define LANG_FL_tInvoice_cAddr2 "cAddr2"
#define LANG_FT_tInvoice_cAddr2 "Street mailing address line 2"
#define LANG_FL_tInvoice_cCity "cCity"
#define LANG_FT_tInvoice_cCity "City"
#define LANG_FL_tInvoice_cState "cState"
#define LANG_FT_tInvoice_cState "State, Province or Locality"
#define LANG_FL_tInvoice_cZip "cZip"
#define LANG_FT_tInvoice_cZip "Postal or Zip code"
#define LANG_FL_tInvoice_cCountry "cCountry"
#define LANG_FT_tInvoice_cCountry "Country"
#define LANG_FL_tInvoice_cCardType "cCardType"
#define LANG_FT_tInvoice_cCardType "Credit Card Type"
#define LANG_FL_tInvoice_cCardNumber "cCardNumber"
#define LANG_FT_tInvoice_cCardNumber "Credit Card Number"
#define LANG_FL_tInvoice_uExpMonth "uExpMonth"
#define LANG_FT_tInvoice_uExpMonth "Credit card expiration month"
#define LANG_FL_tInvoice_uExpYear "uExpYear"
#define LANG_FT_tInvoice_uExpYear "Credit card expiration year"
#define LANG_FL_tInvoice_cCardName "cCardName"
#define LANG_FT_tInvoice_cCardName "Name as appears on credit card"
#define LANG_FL_tInvoice_cShipName "cShipName"
#define LANG_FT_tInvoice_cShipName "Shipping address name"
#define LANG_FL_tInvoice_cShipAddr1 "cShipAddr1"
#define LANG_FT_tInvoice_cShipAddr1 "Shipping street address"
#define LANG_FL_tInvoice_cShipAddr2 "cShipAddr2"
#define LANG_FT_tInvoice_cShipAddr2 "Shipping street address line 2"
#define LANG_FL_tInvoice_cShipCity "cShipCity"
#define LANG_FT_tInvoice_cShipCity "Shipping city"
#define LANG_FL_tInvoice_cShipState "cShipState"
#define LANG_FT_tInvoice_cShipState "Shipping state or province"
#define LANG_FL_tInvoice_cShipZip "cShipZip"
#define LANG_FT_tInvoice_cShipZip "Shipping zip or postal code"
#define LANG_FL_tInvoice_cShipCountry "cShipCountry"
#define LANG_FT_tInvoice_cShipCountry "Shipping country"
#define LANG_FL_tInvoice_cTelephone "cTelephone"
#define LANG_FT_tInvoice_cTelephone "Customer Telephone"
#define LANG_FL_tInvoice_cFax "cFax"
#define LANG_FT_tInvoice_cFax "Customer Fax"
#define LANG_FL_tInvoice_uOwner "uOwner"
#define LANG_FT_tInvoice_uOwner "Record owner"
#define LANG_FL_tInvoice_uCreatedBy "uCreatedBy"
#define LANG_FT_tInvoice_uCreatedBy "uClient for last insert"
#define LANG_FL_tInvoice_uCreatedDate "uCreatedDate"
#define LANG_FT_tInvoice_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tInvoice_uModBy "uModBy"
#define LANG_FT_tInvoice_uModBy "uClient for last update"
#define LANG_FL_tInvoice_uModDate "uModDate"
#define LANG_FT_tInvoice_uModDate "Unix seconds date last update"
#define LANG_FL_tInvoice_uQueueStatus "uQueueStatus"
#define LANG_FT_tInvoice_uQueueStatus "unxsISP tJob queue status"
//tInvoiceMonth
#define LANG_FL_tInvoiceMonth_uInvoiceMonth "uInvoice"
#define LANG_FT_tInvoiceMonth_uInvoiceMonth "Primary Key"
#define LANG_FL_tInvoiceMonth_uShipping "uShipping"
#define LANG_FT_tInvoiceMonth_uShipping "Shipping method for all products on invoice"
#define LANG_FL_tInvoiceMonth_uPayment "uPayment"
#define LANG_FT_tInvoiceMonth_uPayment "Payment method for all products on invoice"
#define LANG_FL_tInvoiceMonth_uInvoiceStatus "uInvoiceStatus"
#define LANG_FT_tInvoiceMonth_uInvoiceStatus "Invoice status"
#define LANG_FL_tInvoiceMonth_uQueueStatus "uQueueStatus"
#define LANG_FT_tInvoiceMonth_uQueueStatus "Queue Status"
#define LANG_FL_tInvoiceMonth_uClient "uClient"
#define LANG_FT_tInvoiceMonth_uClient "Client ID"
#define LANG_FL_tInvoiceMonth_mTotal "mTotal"
#define LANG_FT_tInvoiceMonth_mTotal "Invoice total from tInvoiceItems"
#define LANG_FL_tInvoiceMonth_mSH "mSH"
#define LANG_FT_tInvoiceMonth_mSH "Shipping and handling total"
#define LANG_FL_tInvoiceMonth_mTax "mTax"
#define LANG_FT_tInvoiceMonth_mTax "Total tax"
#define LANG_FL_tInvoiceMonth_cComments "cComments"
#define LANG_FT_tInvoiceMonth_cComments "Customer or our comments about order"
#define LANG_FL_tInvoiceMonth_cAuthCode "cAuthCode"
#define LANG_FT_tInvoiceMonth_cAuthCode "Credit card processor or other authorization code"
#define LANG_FL_tInvoiceMonth_cPnRef "cPnRef"
#define LANG_FT_tInvoiceMonth_cPnRef "Online payment processor tansaction reference"
#define LANG_FL_tInvoiceMonth_uAvsAddr "uAvsAddr"
#define LANG_FT_tInvoiceMonth_uAvsAddr "AVS address verified"
#define LANG_FL_tInvoiceMonth_uAvsZip "uAvsZip"
#define LANG_FT_tInvoiceMonth_uAvsZip "AVS zipcode verified"
#define LANG_FL_tInvoiceMonth_uResultCode "uResultCode"
#define LANG_FT_tInvoiceMonth_uResultCode "Payment processor result code"
#define LANG_FL_tInvoiceMonth_cFirstName "cFirstName"
#define LANG_FT_tInvoiceMonth_cFirstName "First Name"
#define LANG_FL_tInvoiceMonth_cLastName "cLastName"
#define LANG_FT_tInvoiceMonth_cLastName "Last Name"
#define LANG_FL_tInvoiceMonth_cEmail "cEmail"
#define LANG_FT_tInvoiceMonth_cEmail "eMail"
#define LANG_FL_tInvoiceMonth_cAddr1 "cAddr1"
#define LANG_FT_tInvoiceMonth_cAddr1 "Street mailing address"
#define LANG_FL_tInvoiceMonth_cAddr2 "cAddr2"
#define LANG_FT_tInvoiceMonth_cAddr2 "Street mailing address line 2"
#define LANG_FL_tInvoiceMonth_cCity "cCity"
#define LANG_FT_tInvoiceMonth_cCity "City"
#define LANG_FL_tInvoiceMonth_cState "cState"
#define LANG_FT_tInvoiceMonth_cState "State, Province or Locality"
#define LANG_FL_tInvoiceMonth_cZip "cZip"
#define LANG_FT_tInvoiceMonth_cZip "Postal or Zip code"
#define LANG_FL_tInvoiceMonth_cCountry "cCountry"
#define LANG_FT_tInvoiceMonth_cCountry "Country"
#define LANG_FL_tInvoiceMonth_cCardType "cCardType"
#define LANG_FT_tInvoiceMonth_cCardType "Credit Card Type"
#define LANG_FL_tInvoiceMonth_cCardNumber "cCardNumber"
#define LANG_FT_tInvoiceMonth_cCardNumber "Credit Card Number"
#define LANG_FL_tInvoiceMonth_uExpMonth "uExpMonth"
#define LANG_FT_tInvoiceMonth_uExpMonth "Credit card expiration month"
#define LANG_FL_tInvoiceMonth_uExpYear "uExpYear"
#define LANG_FT_tInvoiceMonth_uExpYear "Credit card expiration year"
#define LANG_FL_tInvoiceMonth_cCardName "cCardName"
#define LANG_FT_tInvoiceMonth_cCardName "Name as appears on credit card"
#define LANG_FL_tInvoiceMonth_cShipName "cShipName"
#define LANG_FT_tInvoiceMonth_cShipName "Shipping address name"
#define LANG_FL_tInvoiceMonth_cShipAddr1 "cShipAddr1"
#define LANG_FT_tInvoiceMonth_cShipAddr1 "Shipping street address"
#define LANG_FL_tInvoiceMonth_cShipAddr2 "cShipAddr2"
#define LANG_FT_tInvoiceMonth_cShipAddr2 "Shipping street address line 2"
#define LANG_FL_tInvoiceMonth_cShipCity "cShipCity"
#define LANG_FT_tInvoiceMonth_cShipCity "Shipping city"
#define LANG_FL_tInvoiceMonth_cShipState "cShipState"
#define LANG_FT_tInvoiceMonth_cShipState "Shipping state or province"
#define LANG_FL_tInvoiceMonth_cShipZip "cShipZip"
#define LANG_FT_tInvoiceMonth_cShipZip "Shipping zip or postal code"
#define LANG_FL_tInvoiceMonth_cShipCountry "cShipCountry"
#define LANG_FT_tInvoiceMonth_cShipCountry "Shipping country"
#define LANG_FL_tInvoiceMonth_cTelephone "cTelephone"
#define LANG_FT_tInvoiceMonth_cTelephone "Customer Telephone"
#define LANG_FL_tInvoiceMonth_cFax "cFax"
#define LANG_FT_tInvoiceMonth_cFax "Customer Fax"
#define LANG_FL_tInvoiceMonth_uOwner "uOwner"
#define LANG_FT_tInvoiceMonth_uOwner "Record owner"
#define LANG_FL_tInvoiceMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tInvoiceMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tInvoiceMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tInvoiceMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tInvoiceMonth_uModBy "uModBy"
#define LANG_FT_tInvoiceMonth_uModBy "uClient for last update"
#define LANG_FL_tInvoiceMonth_uModDate "uModDate"
#define LANG_FT_tInvoiceMonth_uModDate "Unix seconds date last update"
//tPaid
#define LANG_FL_tPaid_uPaid "uPaid"
#define LANG_FT_tPaid_uPaid "Primary Key"
//tPaid
#define LANG_FL_tPaid_uPaid "uPaid"
#define LANG_FT_tPaid_uPaid "Primary Key"
#define LANG_FL_tPaid_uPayment "uPayment"
#define LANG_FT_tPaid_uPayment "Payment type"
#define LANG_FL_tPaid_mAmount "mAmount"
#define LANG_FT_tPaid_mAmount "Amount received"
#define LANG_FL_tPaid_uInvoice "uInvoice"
#define LANG_FT_tPaid_uInvoice "Payment corresponds to this invoice"
#define LANG_FL_tPaid_uClient "uClient"
#define LANG_FT_tPaid_uClient "Payment corresponds to this customer"
#define LANG_FL_tPaid_cComment "cComment"
#define LANG_FT_tPaid_cComment "Comments about payment. Details. Check number, etc."
#define LANG_FL_tPaid_uOwner "uOwner"
#define LANG_FT_tPaid_uOwner "Record owner"
#define LANG_FL_tPaid_uCreatedBy "uCreatedBy"
#define LANG_FT_tPaid_uCreatedBy "uClient for last insert"
#define LANG_FL_tPaid_uCreatedDate "uCreatedDate"
#define LANG_FT_tPaid_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tPaid_uModBy "uModBy"
#define LANG_FT_tPaid_uModBy "uClient for last update"
#define LANG_FL_tPaid_uModDate "uModDate"
#define LANG_FT_tPaid_uModDate "Unix seconds date last update"
//tInvoiceItems
#define LANG_FL_tInvoiceItems_uInvoiceItems "uInvoiceItems"
#define LANG_FT_tInvoiceItems_uInvoiceItems "Primary Key"
#define LANG_FL_tInvoiceItems_uInvoice "uInvoice"
#define LANG_FT_tInvoiceItems_uInvoice "FKey"
#define LANG_FL_tInvoiceItems_uInstance "uInstance"
#define LANG_FT_tInvoiceItems_uInstance "Client configuration of product instance"
#define LANG_FL_tInvoiceItems_uClient "uClient"
#define LANG_FT_tInvoiceItems_uClient "FKey"
#define LANG_FL_tInvoiceItems_uProduct "uProduct"
#define LANG_FT_tInvoiceItems_uProduct "FKey"
#define LANG_FL_tInvoiceItems_uQuantity "uQuantity"
#define LANG_FT_tInvoiceItems_uQuantity "Quantity of product ordered"
#define LANG_FL_tInvoiceItems_mPrice "mPrice"
#define LANG_FT_tInvoiceItems_mPrice "Price of product at purchase time"
#define LANG_FL_tInvoiceItems_mTax "mTax"
#define LANG_FT_tInvoiceItems_mTax "Tax for this item (x uQuantity) if applicable"
#define LANG_FL_tInvoiceItems_mSH "mSH"
#define LANG_FT_tInvoiceItems_mSH "Shipping and handling for this item"
#define LANG_FL_tInvoiceItems_mTotal "mTotal"
#define LANG_FT_tInvoiceItems_mTotal "Total for this line"
#define LANG_FL_tInvoiceItems_uOwner "uOwner"
#define LANG_FT_tInvoiceItems_uOwner "Record owner"
#define LANG_FL_tInvoiceItems_uCreatedBy "uCreatedBy"
#define LANG_FT_tInvoiceItems_uCreatedBy "uClient for last insert"
#define LANG_FL_tInvoiceItems_uCreatedDate "uCreatedDate"
#define LANG_FT_tInvoiceItems_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tInvoiceItems_uModBy "uModBy"
#define LANG_FT_tInvoiceItems_uModBy "uClient for last update"
#define LANG_FL_tInvoiceItems_uModDate "uModDate"
#define LANG_FT_tInvoiceItems_uModDate "Unix seconds date last update"

#define LANG_FL_tInvoiceItems_cLabel "cLabel"
#define LANG_FT_tInvoiceItems_cLabel "Short label for item type"

//tInvoiceStatus
#define LANG_FL_tInvoiceStatus_uInvoiceStatus "uInvoiceStatus"
#define LANG_FT_tInvoiceStatus_uInvoiceStatus "Primary Key"
#define LANG_FL_tInvoiceStatus_cLabel "cLabel"
#define LANG_FT_tInvoiceStatus_cLabel "Short label"
#define LANG_FL_tInvoiceStatus_uOwner "uOwner"
#define LANG_FT_tInvoiceStatus_uOwner "Record owner"
#define LANG_FL_tInvoiceStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tInvoiceStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tInvoiceStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tInvoiceStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tInvoiceStatus_uModBy "uModBy"
#define LANG_FT_tInvoiceStatus_uModBy "uClient for last update"
#define LANG_FL_tInvoiceStatus_uModDate "uModDate"
#define LANG_FT_tInvoiceStatus_uModDate "Unix seconds date last update"
//tIsm5
#define LANG_FL_tIsm5_uIsm5 "uIsm5"
#define LANG_FT_tIsm5_uIsm5 "Primary Key"
#define LANG_FL_tIsm5_cLabel "cLabel"
#define LANG_FT_tIsm5_cLabel "Short label"
#define LANG_FL_tIsm5_cComments "cComments"
#define LANG_FT_tIsm5_cComments "Comments/help about query below"
#define LANG_FL_tIsm5_cQuery "cQuery"
#define LANG_FT_tIsm5_cQuery "ism5 query"
#define LANG_FL_tIsm5_cLayout "cLayout"
#define LANG_FT_tIsm5_cLayout "Freeform layout code string"
#define LANG_FL_tIsm5_uVersion "uVersion"
#define LANG_FT_tIsm5_uVersion "ism5 version code"
#define LANG_FL_tIsm5_uPerm "uPerm"
#define LANG_FT_tIsm5_uPerm "uPermLevel equivalent for user level based version of query"
#define LANG_FL_tIsm5_uOwner "uOwner"
#define LANG_FT_tIsm5_uOwner "Record owner"
#define LANG_FL_tIsm5_uCreatedBy "uCreatedBy"
#define LANG_FT_tIsm5_uCreatedBy "uClient for last insert"
#define LANG_FL_tIsm5_uCreatedDate "uCreatedDate"
#define LANG_FT_tIsm5_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tIsm5_uModBy "uModBy"
#define LANG_FT_tIsm5_uModBy "uClient for last update"
#define LANG_FL_tIsm5_uModDate "uModDate"
#define LANG_FT_tIsm5_uModDate "Unix seconds date last update"
//tTemplate
#define LANG_FL_tTemplate_uTemplate "uTemplate"
#define LANG_FT_tTemplate_uTemplate "Primary Key"
#define LANG_FL_tTemplate_cLabel "cLabel"
#define LANG_FT_tTemplate_cLabel "Short label"
#define LANG_FL_tTemplate_cComment "cComment"
#define LANG_FT_tTemplate_cComment "Comments about template below"
#define LANG_FL_tTemplate_cTemplate "cTemplate"
#define LANG_FT_tTemplate_cTemplate "HTML template"
#define LANG_FL_tTemplate_uTemplateSet "uTemplateSet"
#define LANG_FL_tTemplate_uTemplateType "uTemplateType"
#define LANG_FL_tTemplate_uOwner "uOwner"
#define LANG_FT_tTemplate_uOwner "Record owner"
#define LANG_FL_tTemplate_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplate_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplate_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplate_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplate_uModBy "uModBy"
#define LANG_FT_tTemplate_uModBy "uClient for last update"
#define LANG_FL_tTemplate_uModDate "uModDate"
#define LANG_FT_tTemplate_uModDate "Unix seconds date last update"
//tConfiguration
#define LANG_FL_tConfiguration_uConfiguration "uConfiguration"
#define LANG_FT_tConfiguration_uConfiguration "Primary Key"
#define LANG_FL_tConfiguration_cLabel "cLabel"
#define LANG_FT_tConfiguration_cLabel "Short label"
#define LANG_FL_tConfiguration_cValue "cValue"
#define LANG_FT_tConfiguration_cValue "Value of name(cLabel)/value pair"
#define LANG_FL_tConfiguration_cComment "cComment"
#define LANG_FT_tConfiguration_cComment "Comment about this configuration name/value pair"
#define LANG_FL_tConfiguration_uServer "uServer"
#define LANG_FL_tConfiguration_uOwner "uOwner"
#define LANG_FT_tConfiguration_uOwner "Record owner"
#define LANG_FL_tConfiguration_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfiguration_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfiguration_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfiguration_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfiguration_uModBy "uModBy"
#define LANG_FT_tConfiguration_uModBy "uClient for last update"
#define LANG_FL_tConfiguration_uModDate "uModDate"
#define LANG_FT_tConfiguration_uModDate "Unix seconds date last update"
//tPayment
#define LANG_FL_tPayment_uPayment "uPayment"
#define LANG_FT_tPayment_uPayment "Primary Key"
#define LANG_FL_tPayment_cLabel "cLabel"
#define LANG_FT_tPayment_cLabel "Short label"
#define LANG_FL_tPayment_uAvailable "uAvailable"
#define LANG_FT_tPayment_uAvailable "Make availabe to shoppers"
#define LANG_FL_tPayment_uRequireCreditCard "uRequireCreditCard"
#define LANG_FT_tPayment_uRequireCreditCard "Credit card data required for checkout"
#define LANG_FL_tPayment_uOnlineProcess "uOnlineProcess"
#define LANG_FT_tPayment_uOnlineProcess "Use online payment processing"
#define LANG_FL_tPayment_uEmailNotice "uEmailNotice"
#define LANG_FT_tPayment_uEmailNotice "Notify cEmailOrderDesk"
#define LANG_FL_tPayment_uShipOnOrder "uShipOnOrder"
#define LANG_FT_tPayment_uShipOnOrder "Ship when order is placed"
#define LANG_FL_tPayment_cHelpTemplate "cHelpTemplate"
#define LANG_FT_tPayment_cHelpTemplate "tTemplate cLabel name"
#define LANG_FL_tPayment_cInvoiceFooter "cInvoiceFooter"
#define LANG_FT_tPayment_cInvoiceFooter "tTemplate cLabel name for invoice footer"
#define LANG_FL_tPayment_uBillAgain "uBillAgain"
#define LANG_FT_tPayment_uBillAgain "Auto rebill every uPeriod"
#define LANG_FL_tPayment_uTimes "uTimes"
#define LANG_FT_tPayment_uTimes "Auto rebill uTimes. 0 is forever"
#define LANG_FL_tPayment_uPeriod "uPeriod"
#define LANG_FT_tPayment_uPeriod "Auto rebill every uPeriod"
#define LANG_FL_tPayment_mAdjust "mAdjust"
#define LANG_FT_tPayment_mAdjust "Adjust by a negative or positive percentage"
#define LANG_FL_tPayment_uOwner "uOwner"
#define LANG_FT_tPayment_uOwner "Record owner"
#define LANG_FL_tPayment_uCreatedBy "uCreatedBy"
#define LANG_FT_tPayment_uCreatedBy "uClient for last insert"
#define LANG_FL_tPayment_uCreatedDate "uCreatedDate"
#define LANG_FT_tPayment_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tPayment_uModBy "uModBy"
#define LANG_FT_tPayment_uModBy "uClient for last update"
#define LANG_FL_tPayment_uModDate "uModDate"
#define LANG_FT_tPayment_uModDate "Unix seconds date last update"
//tAccountType
#define LANG_FL_tAccountType_uAccountType "uAccountType"
#define LANG_FT_tAccountType_uAccountType "Primary Key"
#define LANG_FL_tAccountType_cLabel "cLabel"
#define LANG_FT_tAccountType_cLabel "Short label"
#define LANG_FL_tAccountType_uOwner "uOwner"
#define LANG_FT_tAccountType_uOwner "Record owner"
#define LANG_FL_tAccountType_uCreatedBy "uCreatedBy"
#define LANG_FT_tAccountType_uCreatedBy "uClient for last insert"
#define LANG_FL_tAccountType_uCreatedDate "uCreatedDate"
#define LANG_FT_tAccountType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tAccountType_uModBy "uModBy"
#define LANG_FT_tAccountType_uModBy "uClient for last update"
#define LANG_FL_tAccountType_uModDate "uModDate"
#define LANG_FT_tAccountType_uModDate "Unix seconds date last update"
//tShipping
#define LANG_FL_tShipping_uShipping "uShipping"
#define LANG_FT_tShipping_uShipping "Primary Key"
#define LANG_FL_tShipping_cLabel "cLabel"
#define LANG_FT_tShipping_cLabel "Short label"
#define LANG_FL_tShipping_cComment "cComment"
#define LANG_FT_tShipping_cComment "Comment about this shipping method"
#define LANG_FL_tShipping_mCost "mCost"
#define LANG_FT_tShipping_mCost "Shipping cost. Depends on calculation method"
#define LANG_FL_tShipping_uMethod "uMethod"
#define LANG_FT_tShipping_uMethod "Calculation method (not used yet)"
#define LANG_FL_tShipping_uParam1 "uParam1"
#define LANG_FT_tShipping_uParam1 "Calculation method parameter 1"
#define LANG_FL_tShipping_uParam2 "uParam2"
#define LANG_FT_tShipping_uParam2 "Calculation method parameter 2"
#define LANG_FL_tShipping_cNumDays "cNumDays"
#define LANG_FT_tShipping_cNumDays "Customer should expect shipment in this number of days"
#define LANG_FL_tShipping_uOwner "uOwner"
#define LANG_FT_tShipping_uOwner "Record owner"
#define LANG_FL_tShipping_uCreatedBy "uCreatedBy"
#define LANG_FT_tShipping_uCreatedBy "uClient for last insert"
#define LANG_FL_tShipping_uCreatedDate "uCreatedDate"
#define LANG_FT_tShipping_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tShipping_uModBy "uModBy"
#define LANG_FT_tShipping_uModBy "uClient for last update"
#define LANG_FL_tShipping_uModDate "uModDate"
#define LANG_FT_tShipping_uModDate "Unix seconds date last update"
//tProductType
#define LANG_FL_tProductType_uProductType "uProductType"
#define LANG_FT_tProductType_uProductType "Primary Key"
#define LANG_FL_tProductType_cLabel "cLabel"
#define LANG_FT_tProductType_cLabel "Short label"
#define LANG_FL_tProductType_uOwner "uOwner"
#define LANG_FT_tProductType_uOwner "Record owner"
#define LANG_FL_tProductType_uCreatedBy "uCreatedBy"
#define LANG_FT_tProductType_uCreatedBy "uClient for last insert"
#define LANG_FL_tProductType_uCreatedDate "uCreatedDate"
#define LANG_FT_tProductType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tProductType_uModBy "uModBy"
#define LANG_FT_tProductType_uModBy "uClient for last update"
#define LANG_FL_tProductType_uModDate "uModDate"
#define LANG_FT_tProductType_uModDate "Unix seconds date last update"
//tMonth
#define LANG_FL_tMonth_uMonth "uMonth"
#define LANG_FT_tMonth_uMonth "Primary Key"
#define LANG_FL_tMonth_cLabel "cLabel"
#define LANG_FT_tMonth_cLabel "Short label"
#define LANG_FL_tMonth_uOwner "uOwner"
#define LANG_FT_tMonth_uOwner "Record owner"
#define LANG_FL_tMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tMonth_uModBy "uModBy"
#define LANG_FT_tMonth_uModBy "uClient for last update"
#define LANG_FL_tMonth_uModDate "uModDate"
#define LANG_FT_tMonth_uModDate "Unix seconds date last update"
//tInvoiceMonth
#define LANG_FL_tInvoiceMonth_uInvoice "uInvoice"
#define LANG_FT_tInvoiceMonth_uInvoice "Primary Key"
#define LANG_FL_tInvoiceMonth_uShipping "uShipping"
#define LANG_FT_tInvoiceMonth_uShipping "Shipping method for all products on invoice"
#define LANG_FL_tInvoiceMonth_uPayment "uPayment"
#define LANG_FT_tInvoiceMonth_uPayment "Payment method for all products on invoice"
#define LANG_FL_tInvoiceMonth_uInvoiceStatus "uInvoiceStatus"
#define LANG_FT_tInvoiceMonth_uInvoiceStatus "Invoice status"
#define LANG_FL_tInvoiceMonth_uClient "uClient"
#define LANG_FT_tInvoiceMonth_uClient "Client ID"
#define LANG_FL_tInvoiceMonth_mTotal "mTotal"
#define LANG_FT_tInvoiceMonth_mTotal "Invoice total from tInvoiceItems"

#define LANG_FL_tInvoiceMonth_mPaid "mPaid"
#define LANG_FT_tInvoiceMonth_mPaid "Invoice total from all tInvoiceItems"

#define LANG_FL_tInvoiceMonth_mSH "mSH"
#define LANG_FT_tInvoiceMonth_mSH "Shipping and handling total"
#define LANG_FL_tInvoiceMonth_mTax "mTax"
#define LANG_FT_tInvoiceMonth_mTax "Total tax"
#define LANG_FL_tInvoiceMonth_cComments "cComments"
#define LANG_FT_tInvoiceMonth_cComments "Customer or our comments about order"
#define LANG_FL_tInvoiceMonth_cAuthCode "cAuthCode"
#define LANG_FT_tInvoiceMonth_cAuthCode "Credit card processor or other authorization code"
#define LANG_FL_tInvoiceMonth_cPnRef "cPnRef"
#define LANG_FT_tInvoiceMonth_cPnRef "Online payment processor tansaction reference"
#define LANG_FL_tInvoiceMonth_uAvsAddr "uAvsAddr"
#define LANG_FT_tInvoiceMonth_uAvsAddr "AVS address verified"
#define LANG_FL_tInvoiceMonth_uAvsZip "uAvsZip"
#define LANG_FT_tInvoiceMonth_uAvsZip "AVS zipcode verified"
#define LANG_FL_tInvoiceMonth_uResultCode "uResultCode"
#define LANG_FT_tInvoiceMonth_uResultCode "Payment processor result code"
#define LANG_FL_tInvoiceMonth_cFirstName "cFirstName"
#define LANG_FT_tInvoiceMonth_cFirstName "First Name"
#define LANG_FL_tInvoiceMonth_cLastName "cLastName"
#define LANG_FT_tInvoiceMonth_cLastName "Last Name"
#define LANG_FL_tInvoiceMonth_cEmail "cEmail"
#define LANG_FT_tInvoiceMonth_cEmail "eMail"
#define LANG_FL_tInvoiceMonth_cAddr1 "cAddr1"
#define LANG_FT_tInvoiceMonth_cAddr1 "Street mailing address"
#define LANG_FL_tInvoiceMonth_cAddr2 "cAddr2"
#define LANG_FT_tInvoiceMonth_cAddr2 "Street mailing address line 2"
#define LANG_FL_tInvoiceMonth_cCity "cCity"
#define LANG_FT_tInvoiceMonth_cCity "City"
#define LANG_FL_tInvoiceMonth_cState "cState"
#define LANG_FT_tInvoiceMonth_cState "State, Province or Locality"
#define LANG_FL_tInvoiceMonth_cZip "cZip"
#define LANG_FT_tInvoiceMonth_cZip "Postal or Zip code"
#define LANG_FL_tInvoiceMonth_cCountry "cCountry"
#define LANG_FT_tInvoiceMonth_cCountry "Country"
#define LANG_FL_tInvoiceMonth_cCardType "cCardType"
#define LANG_FT_tInvoiceMonth_cCardType "Credit Card Type"
#define LANG_FL_tInvoiceMonth_cCardNumber "cCardNumber"
#define LANG_FT_tInvoiceMonth_cCardNumber "Credit Card Number"
#define LANG_FL_tInvoiceMonth_uExpMonth "uExpMonth"
#define LANG_FT_tInvoiceMonth_uExpMonth "Credit card expiration month"
#define LANG_FL_tInvoiceMonth_uExpYear "uExpYear"
#define LANG_FT_tInvoiceMonth_uExpYear "Credit card expiration year"
#define LANG_FL_tInvoiceMonth_cCardName "cCardName"
#define LANG_FT_tInvoiceMonth_cCardName "Name as appears on credit card"
#define LANG_FL_tInvoiceMonth_cShipName "cShipName"
#define LANG_FT_tInvoiceMonth_cShipName "Shipping address name"
#define LANG_FL_tInvoiceMonth_cShipAddr1 "cShipAddr1"
#define LANG_FT_tInvoiceMonth_cShipAddr1 "Shipping street address"
#define LANG_FL_tInvoiceMonth_cShipAddr2 "cShipAddr2"
#define LANG_FT_tInvoiceMonth_cShipAddr2 "Shipping street address line 2"
#define LANG_FL_tInvoiceMonth_cShipCity "cShipCity"
#define LANG_FT_tInvoiceMonth_cShipCity "Shipping city"
#define LANG_FL_tInvoiceMonth_cShipState "cShipState"
#define LANG_FT_tInvoiceMonth_cShipState "Shipping state or province"
#define LANG_FL_tInvoiceMonth_cShipZip "cShipZip"
#define LANG_FT_tInvoiceMonth_cShipZip "Shipping zip or postal code"
#define LANG_FL_tInvoiceMonth_cShipCountry "cShipCountry"
#define LANG_FT_tInvoiceMonth_cShipCountry "Shipping country"
#define LANG_FL_tInvoiceMonth_cTelephone "cTelephone"
#define LANG_FT_tInvoiceMonth_cTelephone "Customer Telephone"
#define LANG_FL_tInvoiceMonth_cFax "cFax"
#define LANG_FT_tInvoiceMonth_cFax "Customer Fax"
#define LANG_FL_tInvoiceMonth_uOwner "uOwner"
#define LANG_FT_tInvoiceMonth_uOwner "Record owner"
#define LANG_FL_tInvoiceMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tInvoiceMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tInvoiceMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tInvoiceMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tInvoiceMonth_uModBy "uModBy"
#define LANG_FT_tInvoiceMonth_uModBy "uClient for last update"
#define LANG_FL_tInvoiceMonth_uModDate "uModDate"
#define LANG_FT_tInvoiceMonth_uModDate "Unix seconds date last update"
//tGlossary
#define LANG_FL_tGlossary_uGlossary "uGlossary"
#define LANG_FT_tGlossary_uGlossary "Primary Key"
#define LANG_FL_tGlossary_cLabel "cLabel"
#define LANG_FT_tGlossary_cLabel "Short label"
#define LANG_FL_tGlossary_cText "cText"
#define LANG_FT_tGlossary_cText "Definition of the label referenced in cLabel"
#define LANG_FL_tGlossary_uOwner "uOwner"
#define LANG_FT_tGlossary_uOwner "Record owner"
#define LANG_FL_tGlossary_uCreatedBy "uCreatedBy"
#define LANG_FT_tGlossary_uCreatedBy "uClient for last insert"
#define LANG_FL_tGlossary_uCreatedDate "uCreatedDate"
#define LANG_FT_tGlossary_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGlossary_uModBy "uModBy"
#define LANG_FT_tGlossary_uModBy "uClient for last update"
#define LANG_FL_tGlossary_uModDate "uModDate"
#define LANG_FT_tGlossary_uModDate "Unix seconds date last update"
//tServer
#define LANG_FL_tServer_uServer "uServer"
#define LANG_FT_tServer_uServer "Primary Key"
#define LANG_FL_tServer_cLabel "cLabel"
#define LANG_FT_tServer_cLabel "Short label"
#define LANG_FL_tServer_uOwner "uOwner"
#define LANG_FT_tServer_uOwner "Record owner"
#define LANG_FL_tServer_uCreatedBy "uCreatedBy"
#define LANG_FT_tServer_uCreatedBy "uClient for last insert"
#define LANG_FL_tServer_uCreatedDate "uCreatedDate"
#define LANG_FT_tServer_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tServer_uModBy "uModBy"
#define LANG_FT_tServer_uModBy "uClient for last update"
#define LANG_FL_tServer_uModDate "uModDate"
#define LANG_FT_tServer_uModDate "Unix seconds date last update"
//tLog
#define LANG_FL_tLog_uLog "uLog"
#define LANG_FT_tLog_uLog "Primary Key"
#define LANG_FL_tLog_cLabel "cLabel"
#define LANG_FT_tLog_cLabel "Short label"
#define LANG_FL_tLog_uLogType "uLogType"
#define LANG_FT_tLog_uLogType "Log Type"
#define LANG_FL_tLog_cHash "cHash"
#define LANG_FT_tLog_cHash "Security hash to complicate tampering"
#define LANG_FL_tLog_uPermLevel "uPermLevel"
#define LANG_FT_tLog_uPermLevel "User Perm Level"
#define LANG_FL_tLog_uLoginClient "uLoginClient"
#define LANG_FT_tLog_uLoginClient "Client Number"
#define LANG_FL_tLog_cLogin "cLogin"
#define LANG_FT_tLog_cLogin "Login name"
#define LANG_FL_tLog_cHost "cHost"
#define LANG_FT_tLog_cHost "Ip Address"
#define LANG_FL_tLog_uTablePK "uTablePK"
#define LANG_FT_tLog_uTablePK "Primar Key of the Table"
#define LANG_FL_tLog_cTableName "cTableName"
#define LANG_FT_tLog_cTableName "Name of the Table"
#define LANG_FL_tLog_cMessage "cMessage"
#define LANG_FT_tLog_cMessage "Message text"
#define LANG_FL_tLog_cServer "cServer"
#define LANG_FT_tLog_cServer "Server name"
#define LANG_FL_tLog_uOwner "uOwner"
#define LANG_FT_tLog_uOwner "Record owner"
#define LANG_FL_tLog_uCreatedBy "uCreatedBy"
#define LANG_FT_tLog_uCreatedBy "uClient for last insert"
#define LANG_FL_tLog_uCreatedDate "uCreatedDate"
#define LANG_FT_tLog_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLog_uModBy "uModBy"
#define LANG_FT_tLog_uModBy "uClient for last update"
#define LANG_FL_tLog_uModDate "uModDate"
#define LANG_FT_tLog_uModDate "Unix seconds date last update"
//tLogType
#define LANG_FL_tLogType_uLogType "uLogType"
#define LANG_FT_tLogType_uLogType "Primary Key"
#define LANG_FL_tLogType_cLabel "cLabel"
#define LANG_FT_tLogType_cLabel "Short label"
#define LANG_FL_tLogType_uOwner "uOwner"
#define LANG_FT_tLogType_uOwner "Record owner"
#define LANG_FL_tLogType_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogType_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogType_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogType_uModBy "uModBy"
#define LANG_FT_tLogType_uModBy "uClient for last update"
#define LANG_FL_tLogType_uModDate "uModDate"
#define LANG_FT_tLogType_uModDate "Unix seconds date last update"
//tLogMonth
#define LANG_FL_tLogMonth_uLog "uLog"
#define LANG_FT_tLogMonth_uLog "Primary Key"
#define LANG_FL_tLogMonth_cLabel "cLabel"
#define LANG_FT_tLogMonth_cLabel "Short label"
#define LANG_FL_tLogMonth_uLogType "uLogType"
#define LANG_FT_tLogMonth_uLogType "Log Type"
#define LANG_FL_tLogMonth_cHash "cHash"
#define LANG_FT_tLogMonth_cHash "Security hash to complicate tampering"
#define LANG_FL_tLogMonth_uPermLevel "uPermLevel"
#define LANG_FT_tLogMonth_uPermLevel "User Perm Level"
#define LANG_FL_tLogMonth_uLoginClient "uLoginClient"
#define LANG_FT_tLogMonth_uLoginClient "Client Number"
#define LANG_FL_tLogMonth_cLogin "cLogin"
#define LANG_FT_tLogMonth_cLogin "Login name"
#define LANG_FL_tLogMonth_cHost "cHost"
#define LANG_FT_tLogMonth_cHost "Ip Address"
#define LANG_FL_tLogMonth_uTablePK "uTablePK"
#define LANG_FT_tLogMonth_uTablePK "Primar Key of the Table"
#define LANG_FL_tLogMonth_cTableName "cTableName"
#define LANG_FT_tLogMonth_cTableName "Name of the Table"
#define LANG_FL_tLogMonth_uOwner "uOwner"
#define LANG_FT_tLogMonth_uOwner "Record owner"
#define LANG_FL_tLogMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogMonth_uModBy "uModBy"
#define LANG_FT_tLogMonth_uModBy "uClient for last update"
#define LANG_FL_tLogMonth_uModDate "uModDate"
//tTemplateSet
#define LANG_FL_tTemplateSet_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplateSet_uTemplateSet "Primary Key"
#define LANG_FL_tTemplateSet_cLabel "cLabel"
#define LANG_FT_tTemplateSet_cLabel "Short label"
#define LANG_FL_tTemplateSet_uOwner "uOwner"
#define LANG_FT_tTemplateSet_uOwner "Record owner"
#define LANG_FL_tTemplateSet_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateSet_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateSet_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateSet_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateSet_uModBy "uModBy"
#define LANG_FT_tTemplateSet_uModBy "uClient for last update"
#define LANG_FL_tTemplateSet_uModDate "uModDate"
#define LANG_FT_tTemplateSet_uModDate "Unix seconds date last update"
//tTemplateType
#define LANG_FL_tTemplateType_uTemplateType "uTemplateType"
#define LANG_FT_tTemplateType_uTemplateType "Primary Key"
#define LANG_FL_tTemplateType_cLabel "cLabel"
#define LANG_FT_tTemplateType_cLabel "Short label"
#define LANG_FL_tTemplateType_uOwner "uOwner"
#define LANG_FT_tTemplateType_uOwner "Record owner"
#define LANG_FL_tTemplateType_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateType_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateType_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateType_uModBy "uModBy"
#define LANG_FT_tTemplateType_uModBy "uClient for last update"
#define LANG_FL_tTemplateType_uModDate "uModDate"
#define LANG_FT_tTemplateType_uModDate "Unix seconds date last update"
//tJobStatus
#define LANG_FL_tJobStatus_uJobStatus "uJobStatus"
#define LANG_FT_tJobStatus_uJobStatus "Primary Key"
#define LANG_FL_tJobStatus_cLabel "cLabel"
#define LANG_FT_tJobStatus_cLabel "Short label"
#define LANG_FL_tJobStatus_uOwner "uOwner"
#define LANG_FT_tJobStatus_uOwner "Record owner"
#define LANG_FL_tJobStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tJobStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tJobStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tJobStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJobStatus_uModBy "uModBy"
#define LANG_FT_tJobStatus_uModBy "uClient for last update"
#define LANG_FL_tJobStatus_uModDate "uModDate"
#define LANG_FT_tJobStatus_uModDate "Unix seconds date last update"
//tMotd
#define LANG_FL_tMotd_uMotd "uMotd"
#define LANG_FT_tMotd_uMotd "Primary Key"
#define LANG_FL_tMotd_cMessage "cMessage"
#define LANG_FT_tMotd_cMessage "MOTD Text"
#define LANG_FL_tMotd_uOwner "uOwner"
#define LANG_FT_tMotd_uOwner "Record owner"
#define LANG_FL_tMotd_uCreatedBy "uCreatedBy"
#define LANG_FT_tMotd_uCreatedBy "uClient for last insert"
#define LANG_FL_tMotd_uCreatedDate "uCreatedDate"
#define LANG_FT_tMotd_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tMotd_uModBy "uModBy"
#define LANG_FT_tMotd_uModBy "uClient for last update"
#define LANG_FL_tMotd_uModDate "uModDate"
#define LANG_FT_tMotd_uModDate "Unix seconds date last update"

