// $Id$
// English: USA
// Navigation bar buttons and results

#define LANG_NB_LIST "List"
#define LANG_NB_MODIFY "Modify"
#define LANG_NB_CONFIRMMOD "Confirm Modify"
#define LANG_NB_NEW "New"
#define LANG_NB_DELETE "Delete"
#define LANG_NB_CONFIRMNEW "Create New Record"
#define LANG_NBB_CONFIRMNEW "<input class=lrevButton title='Double check!' type=submit name=gcCommand value=\"Create New Record\">"
#define LANG_NB_CONFIRMDEL "Confirm Delete"
#define LANG_NBB_CONFIRMDEL "<input class=lwarnButton title='No undo available!' type=submit name=gcCommand value=\"Confirm Delete\">"
#define LANG_NBB_CONFIRMMOD "<input class=lalertButton title='Double check!' type=submit name=gcCommand value=\"Confirm Modify\">"


#define LANG_NBR_FOUND " Found"
#define LANG_NBR_MODIFIED " Modified"
#define LANG_NBR_NEW " New"
#define LANG_NBR_NORECS " No records found"
#define LANG_NBRF_SHOWING " (Showing %lu of %d)"

#define LANG_NBR_RECEXISTS "<blink>Record already exists"
#define LANG_NBR_NEWRECADDED "New record %u added"
#define LANG_NBR_RECDELETED "Record Deleted"
#define LANG_NBR_RECNOTDELETED "Record Not Deleted"
#define LANG_NBR_RECNOTEXIST "<blink>Record does not exist"
#define LANG_NBR_MULTRECS "<blink>Multiple rows!"
#define LANG_NBR_EXTMOD "<blink>This record was just modified by another user!"
#define LANG_NBRF_REC_MODIFIED "record %s modified"

#define LANG_NBB_SKIPFIRST "<input style='width:30px;' title=\"Skip to first record\" type=submit name=gcFind value=\"<<\" >"
#define LANG_NBB_SKIPBACK "<input style='width:30px;' title=\"Go back one record\" type=submit name=gcFind value=\"< \" >"
#define LANG_NBB_SKIPNEXT "<input style='width:30px;' title=\"Advance to next record\" type=submit name=gcFind value=\" >\" >"
#define LANG_NBB_SKIPLAST "<input style='width:30px;' title=\"Skip to last record\" type=submit name=gcFind value=\">>\" >\n"

//Modified for local .h use
#define LANG_NBB_NEWREV "<input class=revButton title=\"Create new record\" type=submit name=gcCommand value=New>"
#define LANG_NBB_NEW "<input  title=\"Create new record\" type=submit name=gcCommand value=New>"
#define LANG_NBB_DELETE "<input class=warnButton title=\"Delete current record\" type=submit name=gcCommand value=Delete>"
#define LANG_NBB_MODIFY "<input class=alertButton title=\"Modify current record\" type=submit name=gcCommand value=Modify>"

#define LANG_NBB_LIST "<input title=\"Paginated listing of all records\" type=submit name=gcFind value=List>"
#define LANG_NBB_SEARCH "<input class=revButton title=\"Find record with parameters set below\" type=submit name=gcFind value=Search>"

#define LANG_PAGEMACHINE_HINT "No matching records found.<br>"
#define LANG_PAGEMACHINE_SHOWING "Page %d/%d (Records %d-%d of %d)\n"
#define LANG_PAGEMACHINE_SEARCH "<input type=submit name=gcFind value=Search >"
#define LANG_PAGEMACHINE_SEARCHBUTTON "Search"

//tTemplate
#define LANG_FL_tTemplate_uTemplate "uTemplate"
#define LANG_FT_tTemplate_uTemplate "Primary Key"
#define LANG_FL_tTemplate_cLabel "cLabel"
#define LANG_FT_tTemplate_cLabel "Short label"
#define LANG_FL_tTemplate_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplate_uTemplateSet "Short label"
#define LANG_FL_tTemplate_uTemplateType "uTemplateType"
#define LANG_FT_tTemplate_uTemplateType "Short label"
#define LANG_FL_tTemplate_cComment "cComment"
#define LANG_FT_tTemplate_cComment "About the template"
#define LANG_FL_tTemplate_cTemplate "cTemplate"
#define LANG_FT_tTemplate_cTemplate "Template itself"
#define LANG_FL_tTemplate_uOwner "uOwner"
#define LANG_FT_tTemplate_uOwner "Record owner"
#define LANG_FL_tTemplate_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplate_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplate_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplate_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplate_uModBy "uModBy"
#define LANG_FT_tTemplate_uModBy "uClient for last update"
#define LANG_FL_tTemplate_uModDate "uModDate"
#define LANG_FT_tTemplate_uModDate "Unix seconds date last update"
//tTemplateSet
#define LANG_FL_tTemplateSet_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplateSet_uTemplateSet "Primary Key"
#define LANG_FL_tTemplateSet_cLabel "cLabel"
#define LANG_FT_tTemplateSet_cLabel "Short label"
#define LANG_FL_tTemplateSet_uOwner "uOwner"
#define LANG_FT_tTemplateSet_uOwner "Record owner"
#define LANG_FL_tTemplateSet_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateSet_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateSet_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateSet_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateSet_uModBy "uModBy"
#define LANG_FT_tTemplateSet_uModBy "uClient for last update"
#define LANG_FL_tTemplateSet_uModDate "uModDate"
#define LANG_FT_tTemplateSet_uModDate "Unix seconds date last update"
//tTemplateType
#define LANG_FL_tTemplateType_uTemplateType "uTemplateType"
#define LANG_FT_tTemplateType_uTemplateType "Primary Key"
#define LANG_FL_tTemplateType_cLabel "cLabel"
#define LANG_FT_tTemplateType_cLabel "Short label"
#define LANG_FL_tTemplateType_uOwner "uOwner"
#define LANG_FT_tTemplateType_uOwner "Record owner"
#define LANG_FL_tTemplateType_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateType_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateType_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateType_uModBy "uModBy"
#define LANG_FT_tTemplateType_uModBy "uClient for last update"
#define LANG_FL_tTemplateType_uModDate "uModDate"
#define LANG_FT_tTemplateType_uModDate "Unix seconds date last update"
//tConfiguration
#define LANG_FL_tConfiguration_uConfiguration "uConfiguration"
#define LANG_FT_tConfiguration_uConfiguration "Primary Key"
#define LANG_FL_tConfiguration_uServer "uServer"
#define LANG_FT_tConfiguration_uServer "uServer"
#define LANG_FL_tConfiguration_cLabel "cLabel"
#define LANG_FT_tConfiguration_cLabel "cLabel is Name of Name/Value Pair"
#define LANG_FL_tConfiguration_cValue "cValue"
#define LANG_FT_tConfiguration_cValue "Value of name(cLabel)/value pair"
#define LANG_FL_tConfiguration_cComment "cComment"
#define LANG_FT_tConfiguration_cComment "Comment about this configuration name/value pair"
#define LANG_FL_tConfiguration_uOwner "uOwner"
#define LANG_FT_tConfiguration_uOwner "Record owner"
#define LANG_FL_tConfiguration_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfiguration_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfiguration_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfiguration_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfiguration_uModBy "uModBy"
#define LANG_FT_tConfiguration_uModBy "uClient for last update"
#define LANG_FL_tConfiguration_uModDate "uModDate"
#define LANG_FT_tConfiguration_uModDate "Unix seconds date last update"
//tLog
#define LANG_FL_tLog_uLog "uLog"
#define LANG_FT_tLog_uLog "Primary Key"
#define LANG_FL_tLog_cLabel "cLabel"
#define LANG_FT_tLog_cLabel "Short label"
#define LANG_FL_tLog_uLogType "uLogType"
#define LANG_FT_tLog_uLogType "Log Type"
#define LANG_FL_tLog_cHash "cHash"
#define LANG_FT_tLog_cHash "Security hash to complicate tampering"
#define LANG_FL_tLog_uPermLevel "uPermLevel"
#define LANG_FT_tLog_uPermLevel "User Perm Level"
#define LANG_FL_tLog_uLoginClient "uLoginClient"
#define LANG_FT_tLog_uLoginClient "Client Number"
#define LANG_FL_tLog_cLogin "cLogin"
#define LANG_FT_tLog_cLogin "Login name"
#define LANG_FL_tLog_cHost "cHost"
#define LANG_FT_tLog_cHost "Ip Address"
#define LANG_FL_tLog_uTablePK "uTablePK"
#define LANG_FT_tLog_uTablePK "Primar Key of the Table"
#define LANG_FL_tLog_cTableName "cTableName"
#define LANG_FT_tLog_cTableName "Name of the Table"
#define LANG_FL_tLog_cMessage "cMessage"
#define LANG_FT_tLog_cMessage "Message text"
#define LANG_FL_tLog_cServer "cServer"
#define LANG_FT_tLog_cServer "Server name"
#define LANG_FL_tLog_uOwner "uOwner"
#define LANG_FT_tLog_uOwner "Record owner"
#define LANG_FL_tLog_uCreatedBy "uCreatedBy"
#define LANG_FT_tLog_uCreatedBy "uClient for last insert"
#define LANG_FL_tLog_uCreatedDate "uCreatedDate"
#define LANG_FT_tLog_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLog_uModBy "uModBy"
#define LANG_FT_tLog_uModBy "uClient for last update"
#define LANG_FL_tLog_uModDate "uModDate"
#define LANG_FT_tLog_uModDate "Unix seconds date last update"
//tLogType
#define LANG_FL_tLogType_uLogType "uLogType"
#define LANG_FT_tLogType_uLogType "Primary Key"
#define LANG_FL_tLogType_cLabel "cLabel"
#define LANG_FT_tLogType_cLabel "Short label"
#define LANG_FL_tLogType_uOwner "uOwner"
#define LANG_FT_tLogType_uOwner "Record owner"
#define LANG_FL_tLogType_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogType_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogType_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogType_uModBy "uModBy"
#define LANG_FT_tLogType_uModBy "uClient for last update"
#define LANG_FL_tLogType_uModDate "uModDate"
#define LANG_FT_tLogType_uModDate "Unix seconds date last update"
//tLogMonth
#define LANG_FL_tLogMonth_uLog "uLog"
#define LANG_FT_tLogMonth_uLog "Primary Key"
#define LANG_FL_tLogMonth_cLabel "cLabel"
#define LANG_FT_tLogMonth_cLabel "Short label"
#define LANG_FL_tLogMonth_uLogType "uLogType"
#define LANG_FT_tLogMonth_uLogType "Log Type"
#define LANG_FL_tLogMonth_cHash "cHash"
#define LANG_FT_tLogMonth_cHash "Security hash to complicate tampering"
#define LANG_FL_tLogMonth_uPermLevel "uPermLevel"
#define LANG_FT_tLogMonth_uPermLevel "User Perm Level"
#define LANG_FL_tLogMonth_uLoginClient "uLoginClient"
#define LANG_FT_tLogMonth_uLoginClient "Client Number"
#define LANG_FL_tLogMonth_cLogin "cLogin"
#define LANG_FT_tLogMonth_cLogin "Login name"
#define LANG_FL_tLogMonth_cHost "cHost"
#define LANG_FT_tLogMonth_cHost "Ip Address"
#define LANG_FL_tLogMonth_uTablePK "uTablePK"
#define LANG_FT_tLogMonth_uTablePK "Primar Key of the Table"
#define LANG_FL_tLogMonth_cTableName "cTableName"
#define LANG_FT_tLogMonth_cTableName "Name of the Table"
#define LANG_FL_tLogMonth_uOwner "uOwner"
#define LANG_FT_tLogMonth_uOwner "Record owner"
#define LANG_FL_tLogMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogMonth_uModBy "uModBy"
#define LANG_FT_tLogMonth_uModBy "uClient for last update"
#define LANG_FL_tLogMonth_uModDate "uModDate"
#define LANG_FT_tLogMonth_uModDate "Unix seconds date last update"
//tClient
#define LANG_FL_tClient_uClient "uClient"
#define LANG_FT_tClient_uClient "Primary Key"
#define LANG_FL_tClient_cLabel "cLabel"
#define LANG_FT_tClient_cLabel "Short label"
#define LANG_FL_tClient_cInfo "cInfo"
#define LANG_FT_tClient_cInfo "Unformatted info/address etc."
#define LANG_FL_tClient_cEmail "cEmail"
#define LANG_FT_tClient_cEmail "Main Email"
#define LANG_FL_tClient_cCode "cCode"
#define LANG_FT_tClient_cCode "Enterprise wide customer/contact tracking"
#define LANG_FL_tClient_uOwner "uOwner"
#define LANG_FT_tClient_uOwner "Record owner"
#define LANG_FL_tClient_uCreatedBy "uCreatedBy"
#define LANG_FT_tClient_uCreatedBy "uClient for last insert"
#define LANG_FL_tClient_uCreatedDate "uCreatedDate"
#define LANG_FT_tClient_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tClient_uModBy "uModBy"
#define LANG_FT_tClient_uModBy "uClient for last update"
#define LANG_FL_tClient_uModDate "uModDate"
#define LANG_FT_tClient_uModDate "Unix seconds date last update"
//tAuthorize
#define LANG_FL_tAuthorize_uAuthorize "uAuthorize"
#define LANG_FT_tAuthorize_uAuthorize "Primary Key"
#define LANG_FL_tAuthorize_cLabel "cLabel"
#define LANG_FT_tAuthorize_cLabel "Short label"
#define LANG_FL_tAuthorize_cIpMask "cIpMask"
#define LANG_FT_tAuthorize_cIpMask "Allow user from this IP"
#define LANG_FL_tAuthorize_uPerm "uPerm"
#define LANG_FT_tAuthorize_uPerm "User permission level"
#define LANG_FL_tAuthorize_uCertClient "uCertClient"
#define LANG_FT_tAuthorize_uCertClient "User uClient"
#define LANG_FL_tAuthorize_cPasswd "cPasswd"
#define LANG_FT_tAuthorize_cPasswd "Encrypted cgi login password"
#define LANG_FL_tAuthorize_cClrPasswd "cClrPasswd"
#define LANG_FT_tAuthorize_cClrPasswd "Optionally used non encrypted login password"
#define LANG_FL_tAuthorize_uOwner "uOwner"
#define LANG_FT_tAuthorize_uOwner "Record owner"
#define LANG_FL_tAuthorize_uCreatedBy "uCreatedBy"
#define LANG_FT_tAuthorize_uCreatedBy "uClient for last insert"
#define LANG_FL_tAuthorize_uCreatedDate "uCreatedDate"
#define LANG_FT_tAuthorize_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tAuthorize_uModBy "uModBy"
#define LANG_FT_tAuthorize_uModBy "uClient for last update"
#define LANG_FL_tAuthorize_uModDate "uModDate"
#define LANG_FT_tAuthorize_uModDate "Unix seconds date last update"
//tMonth
#define LANG_FL_tMonth_uMonth "uMonth"
#define LANG_FT_tMonth_uMonth "Primary Key"
#define LANG_FL_tMonth_cLabel "cLabel"
#define LANG_FT_tMonth_cLabel "Name of Archive Table Ex. tNov2009"
#define LANG_FL_tMonth_uOwner "uOwner"
#define LANG_FT_tMonth_uOwner "Record owner"
#define LANG_FL_tMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tMonth_uModBy "uModBy"
#define LANG_FT_tMonth_uModBy "uClient for last update"
#define LANG_FL_tMonth_uModDate "uModDate"
#define LANG_FT_tMonth_uModDate "Unix seconds date last update"
//tGlossary
#define LANG_FL_tGlossary_uGlossary "uGlossary"
#define LANG_FT_tGlossary_uGlossary "Primary Key"
#define LANG_FL_tGlossary_cLabel "cLabel"
#define LANG_FT_tGlossary_cLabel "Short label"
#define LANG_FL_tGlossary_cText "cText"
#define LANG_FT_tGlossary_cText "Definition of the label referenced in cLabel"
#define LANG_FL_tGlossary_uOwner "uOwner"
#define LANG_FT_tGlossary_uOwner "Record owner"
#define LANG_FL_tGlossary_uCreatedBy "uCreatedBy"
#define LANG_FT_tGlossary_uCreatedBy "uClient for last insert"
#define LANG_FL_tGlossary_uCreatedDate "uCreatedDate"
#define LANG_FT_tGlossary_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGlossary_uModBy "uModBy"
#define LANG_FT_tGlossary_uModBy "uClient for last update"
#define LANG_FL_tGlossary_uModDate "uModDate"
#define LANG_FT_tGlossary_uModDate "Unix seconds date last update"
//tJob
#define LANG_FL_tJob_uJob "uJob"
#define LANG_FT_tJob_uJob "Primary Key"
#define LANG_FL_tJob_cLabel "cLabel"
#define LANG_FT_tJob_cLabel "Label for user feedback"
#define LANG_FL_tJob_cServer "cServer"
#define LANG_FT_tJob_cServer "Server name ip or any server"
#define LANG_FL_tJob_cJobName "cJobName"
#define LANG_FT_tJob_cJobName "Subsystem.Function style job name"
#define LANG_FL_tJob_uJobTarget "uJobTarget"
#define LANG_FT_tJob_uJobTarget "Owner of resources created/mod"
#define LANG_FL_tJob_uJobTargetUser "uJobTargetUser"
#define LANG_FT_tJob_uJobTargetUser "Target User ID"
#define LANG_FL_tJob_cJobData "cJobData"
#define LANG_FT_tJob_cJobData "Remote subsystem server function arguments"
#define LANG_FL_tJob_uJobDate "uJobDate"
#define LANG_FT_tJob_uJobDate "Unix seconds for job to start to be considered"
#define LANG_FL_tJob_uJobStatus "uJobStatus"
#define LANG_FT_tJob_uJobStatus "Waiting, being processed, done, error"
#define LANG_FL_tJob_cRemoteMsg "cRemoteMsg"
#define LANG_FT_tJob_cRemoteMsg "Remote subsytem error message"
#define LANG_FL_tJob_uOwner "uOwner"
#define LANG_FT_tJob_uOwner "Record owner"
#define LANG_FL_tJob_uCreatedBy "uCreatedBy"
#define LANG_FT_tJob_uCreatedBy "uClient for last insert"
#define LANG_FL_tJob_uCreatedDate "uCreatedDate"
#define LANG_FT_tJob_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJob_uModBy "uModBy"
#define LANG_FT_tJob_uModBy "uClient for last update"
#define LANG_FL_tJob_uModDate "uModDate"
#define LANG_FT_tJob_uModDate "Unix seconds date last update"
//tServer
#define LANG_FL_tServer_uServer "uServer"
#define LANG_FT_tServer_uServer "Primary Key"
#define LANG_FL_tServer_cLabel "cLabel"
#define LANG_FT_tServer_cLabel "Short label"
#define LANG_FL_tServer_uOwner "uOwner"
#define LANG_FT_tServer_uOwner "Record owner"
#define LANG_FL_tServer_uCreatedBy "uCreatedBy"
#define LANG_FT_tServer_uCreatedBy "uClient for last insert"
#define LANG_FL_tServer_uCreatedDate "uCreatedDate"
#define LANG_FT_tServer_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tServer_uModBy "uModBy"
#define LANG_FT_tServer_uModBy "uClient for last update"
#define LANG_FL_tServer_uModDate "uModDate"
#define LANG_FT_tServer_uModDate "Unix seconds date last update"
//tJobStatus
#define LANG_FL_tJobStatus_uJobStatus "uJobStatus"
#define LANG_FT_tJobStatus_uJobStatus "Primary Key"
#define LANG_FL_tJobStatus_cLabel "cLabel"
#define LANG_FT_tJobStatus_cLabel "Short label"
#define LANG_FL_tJobStatus_uOwner "uOwner"
#define LANG_FT_tJobStatus_uOwner "Record owner"
#define LANG_FL_tJobStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tJobStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tJobStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tJobStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJobStatus_uModBy "uModBy"
#define LANG_FT_tJobStatus_uModBy "uClient for last update"
#define LANG_FL_tJobStatus_uModDate "uModDate"
#define LANG_FT_tJobStatus_uModDate "Unix seconds date last update"
//tStatus
#define LANG_FL_tStatus_uStatus "uStatus"
#define LANG_FT_tStatus_uStatus "Primary Key"
#define LANG_FL_tStatus_cLabel "cLabel"
#define LANG_FT_tStatus_cLabel "Short label"
#define LANG_FL_tStatus_uOwner "uOwner"
#define LANG_FT_tStatus_uOwner "Record owner"
#define LANG_FL_tStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tStatus_uModBy "uModBy"
#define LANG_FT_tStatus_uModBy "uClient for last update"
#define LANG_FL_tStatus_uModDate "uModDate"
#define LANG_FT_tStatus_uModDate "Unix seconds date last update"
//tDatacenter
#define LANG_FL_tDatacenter_uDatacenter "uDatacenter"
#define LANG_FT_tDatacenter_uDatacenter "Primary Key"
#define LANG_FL_tDatacenter_cLabel "cLabel"
#define LANG_FT_tDatacenter_cLabel "Short label"
#define LANG_FL_tDatacenter_uStatus "uStatus"
#define LANG_FT_tDatacenter_uStatus "Status of Datacenter"
#define LANG_FL_tDatacenter_uOwner "uOwner"
#define LANG_FT_tDatacenter_uOwner "Record owner"
#define LANG_FL_tDatacenter_uCreatedBy "uCreatedBy"
#define LANG_FT_tDatacenter_uCreatedBy "uClient for last insert"
#define LANG_FL_tDatacenter_uCreatedDate "uCreatedDate"
#define LANG_FT_tDatacenter_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tDatacenter_uModBy "uModBy"
#define LANG_FT_tDatacenter_uModBy "uClient for last update"
#define LANG_FL_tDatacenter_uModDate "uModDate"
#define LANG_FT_tDatacenter_uModDate "Unix seconds date last update"
//tNode
#define LANG_FL_tNode_uNode "uNode"
#define LANG_FT_tNode_uNode "Primary Key"
#define LANG_FL_tNode_cLabel "cLabel"
#define LANG_FT_tNode_cLabel "Short label"
#define LANG_FL_tNode_uDatacenter "uDatacenter"
#define LANG_FT_tNode_uDatacenter "Belongs to this Datacenter"
#define LANG_FL_tNode_uStatus "uStatus"
#define LANG_FT_tNode_uStatus "Status of Hardware Node"
#define LANG_FL_tNode_uOwner "uOwner"
#define LANG_FT_tNode_uOwner "Record owner"
#define LANG_FL_tNode_uCreatedBy "uCreatedBy"
#define LANG_FT_tNode_uCreatedBy "uClient for last insert"
#define LANG_FL_tNode_uCreatedDate "uCreatedDate"
#define LANG_FT_tNode_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tNode_uModBy "uModBy"
#define LANG_FT_tNode_uModBy "uClient for last update"
#define LANG_FL_tNode_uModDate "uModDate"
#define LANG_FT_tNode_uModDate "Unix seconds date last update"
//tContainer
#define LANG_FL_tContainer_uContainer "uContainer"
#define LANG_FT_tContainer_uContainer "Primary Key"
#define LANG_FL_tContainer_cLabel "cLabel"
#define LANG_FT_tContainer_cLabel "Short label"
#define LANG_FL_tContainer_cHostname "cHostname"
#define LANG_FT_tContainer_cHostname "FQDN Hostname"
#define LANG_FL_tContainer_uIPv4 "uIPv4"
#define LANG_FT_tContainer_uIPv4 "First IPv4 Number"
#define LANG_FL_tContainer_uVeth "uVeth"
#define LANG_FT_tContainer_uVeth "Default VENET, yes VETH networking"
#define LANG_FL_tContainer_uOSTemplate "uOSTemplate"
#define LANG_FT_tContainer_uOSTemplate "Container OS Template"
#define LANG_FL_tContainer_uConfig "uConfig"
#define LANG_FT_tContainer_uConfig "Container Config File Used on Creation"
#define LANG_FL_tContainer_uNameserver "uNameserver"
#define LANG_FT_tContainer_uNameserver "Container Resolver Nameserver Set"
#define LANG_FL_tContainer_uSearchdomain "uSearchdomain"
#define LANG_FT_tContainer_uSearchdomain "Container Resolver Searchdomain"
#define LANG_FL_tContainer_uDatacenter "uDatacenter"
#define LANG_FT_tContainer_uDatacenter "Belongs to this Datacenter"
#define LANG_FL_tContainer_uNode "uNode"
#define LANG_FT_tContainer_uNode "Running on this Node"
#define LANG_FL_tContainer_uStatus "uStatus"
#define LANG_FT_tContainer_uStatus "Status of Container"
#define LANG_FL_tContainer_uOwner "uOwner"
#define LANG_FT_tContainer_uOwner "Record owner"
#define LANG_FL_tContainer_uCreatedBy "uCreatedBy"
#define LANG_FT_tContainer_uCreatedBy "uClient for last insert"
#define LANG_FL_tContainer_uCreatedDate "uCreatedDate"
#define LANG_FT_tContainer_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tContainer_uModBy "uModBy"
#define LANG_FT_tContainer_uModBy "uClient for last update"
#define LANG_FL_tContainer_uModDate "uModDate"
#define LANG_FT_tContainer_uModDate "Unix seconds date last update"
#define LANG_FL_tContainer_uSource "uSource"
#define LANG_FT_tContainer_uSource "Source of a cloned container"
#define LANG_FL_tContainer_uBackupDate "uBackupDate"
#define LANG_FT_tContainer_uBackupDate "Unix seconds date last backup"
#define LANG_FL_tContainer_uContainerType "uContainerType"
#define LANG_FT_tContainer_uContainerType "VZ, Google VM, etc."
#define LANG_FL_tContainer_cComment "cComment"
#define LANG_FT_tContainer_cComment "Container notes"
//tProperty
#define LANG_FL_tProperty_uProperty "uProperty"
#define LANG_FT_tProperty_uProperty "Primary Key"
#define LANG_FL_tProperty_cName "cName"
#define LANG_FT_tProperty_cName "Property Name"
#define LANG_FL_tProperty_cValue "cValue"
#define LANG_FT_tProperty_cValue "Value of property"
#define LANG_FL_tProperty_uType "uType"
#define LANG_FT_tProperty_uType "Type of property"
#define LANG_FL_tProperty_uKey "uKey"
#define LANG_FT_tProperty_uKey "Abstract FK"
#define LANG_FL_tProperty_uOwner "uOwner"
#define LANG_FT_tProperty_uOwner "Record owner"
#define LANG_FL_tProperty_uCreatedBy "uCreatedBy"
#define LANG_FT_tProperty_uCreatedBy "uClient for last insert"
#define LANG_FL_tProperty_uCreatedDate "uCreatedDate"
#define LANG_FT_tProperty_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tProperty_uModBy "uModBy"
#define LANG_FT_tProperty_uModBy "uClient for last update"
#define LANG_FL_tProperty_uModDate "uModDate"
#define LANG_FT_tProperty_uModDate "Unix seconds date last update"
//tType
#define LANG_FL_tType_uType "uType"
#define LANG_FT_tType_uType "Primary Key"
#define LANG_FL_tType_cLabel "cLabel"
#define LANG_FT_tType_cLabel "Short label"
#define LANG_FL_tType_uOwner "uOwner"
#define LANG_FT_tType_uOwner "Record owner"
#define LANG_FL_tType_uCreatedBy "uCreatedBy"
#define LANG_FT_tType_uCreatedBy "uClient for last insert"
#define LANG_FL_tType_uCreatedDate "uCreatedDate"
#define LANG_FT_tType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tType_uModBy "uModBy"
#define LANG_FT_tType_uModBy "uClient for last update"
#define LANG_FL_tType_uModDate "uModDate"
#define LANG_FT_tType_uModDate "Unix seconds date last update"
//tContainerType
#define LANG_FL_tContainerType_uType "uType"
#define LANG_FT_tContainerType_uType "Primary Key"
#define LANG_FL_tContainerType_cLabel "cLabel"
#define LANG_FT_tContainerType_cLabel "Short label"
#define LANG_FL_tContainerType_uOwner "uOwner"
#define LANG_FT_tContainerType_uOwner "Record owner"
#define LANG_FL_tContainerType_uCreatedBy "uCreatedBy"
#define LANG_FT_tContainerType_uCreatedBy "uClient for last insert"
#define LANG_FL_tContainerType_uCreatedDate "uCreatedDate"
#define LANG_FT_tContainerType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tContainerType_uModBy "uModBy"
#define LANG_FT_tContainerType_uModBy "uClient for last update"
#define LANG_FL_tContainerType_uModDate "uModDate"
#define LANG_FT_tContainerType_uModDate "Unix seconds date last update"
//tPerm
#define LANG_FL_tPerm_uPerm "uPerm"
#define LANG_FT_tPerm_uPerm "Primary Key"
#define LANG_FL_tPerm_cLabel "cLabel"
#define LANG_FT_tPerm_cLabel "Short label"
#define LANG_FL_tPerm_uOwner "uOwner"
#define LANG_FT_tPerm_uOwner "Record owner"
#define LANG_FL_tPerm_uCreatedBy "uCreatedBy"
#define LANG_FT_tPerm_uCreatedBy "uClient for last insert"
#define LANG_FL_tPerm_uCreatedDate "uCreatedDate"
#define LANG_FT_tPerm_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tPerm_uModBy "uModBy"
#define LANG_FT_tPerm_uModBy "uClient for last update"
#define LANG_FL_tPerm_uModDate "uModDate"
#define LANG_FT_tPerm_uModDate "Unix seconds date last update"
//tOSTemplate
#define LANG_FL_tOSTemplate_uOSTemplate "uOSTemplate"
#define LANG_FT_tOSTemplate_uOSTemplate "Primary Key"
#define LANG_FL_tOSTemplate_cLabel "cLabel"
#define LANG_FT_tOSTemplate_cLabel "Short label"
#define LANG_FL_tOSTemplate_uOwner "uOwner"
#define LANG_FT_tOSTemplate_uOwner "Record owner"
#define LANG_FL_tOSTemplate_uCreatedBy "uCreatedBy"
#define LANG_FT_tOSTemplate_uCreatedBy "uClient for last insert"
#define LANG_FL_tOSTemplate_uCreatedDate "uCreatedDate"
#define LANG_FT_tOSTemplate_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tOSTemplate_uModBy "uModBy"
#define LANG_FT_tOSTemplate_uModBy "uClient for last update"
#define LANG_FL_tOSTemplate_uModDate "uModDate"
#define LANG_FT_tOSTemplate_uModDate "Unix seconds date last update"
//tNameserver
#define LANG_FL_tNameserver_uNameserver "uNameserver"
#define LANG_FT_tNameserver_uNameserver "Primary Key"
#define LANG_FL_tNameserver_cLabel "cLabel"
#define LANG_FT_tNameserver_cLabel "Short label"
#define LANG_FL_tNameserver_uOwner "uOwner"
#define LANG_FT_tNameserver_uOwner "Record owner"
#define LANG_FL_tNameserver_uCreatedBy "uCreatedBy"
#define LANG_FT_tNameserver_uCreatedBy "uClient for last insert"
#define LANG_FL_tNameserver_uCreatedDate "uCreatedDate"
#define LANG_FT_tNameserver_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tNameserver_uModBy "uModBy"
#define LANG_FT_tNameserver_uModBy "uClient for last update"
#define LANG_FL_tNameserver_uModDate "uModDate"
#define LANG_FT_tNameserver_uModDate "Unix seconds date last update"
//tSearchdomain
#define LANG_FL_tSearchdomain_uSearchdomain "uSearchdomain"
#define LANG_FT_tSearchdomain_uSearchdomain "Primary Key"
#define LANG_FL_tSearchdomain_cLabel "cLabel"
#define LANG_FT_tSearchdomain_cLabel "Short label"
#define LANG_FL_tSearchdomain_uOwner "uOwner"
#define LANG_FT_tSearchdomain_uOwner "Record owner"
#define LANG_FL_tSearchdomain_uCreatedBy "uCreatedBy"
#define LANG_FT_tSearchdomain_uCreatedBy "uClient for last insert"
#define LANG_FL_tSearchdomain_uCreatedDate "uCreatedDate"
#define LANG_FT_tSearchdomain_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tSearchdomain_uModBy "uModBy"
#define LANG_FT_tSearchdomain_uModBy "uClient for last update"
#define LANG_FL_tSearchdomain_uModDate "uModDate"
#define LANG_FT_tSearchdomain_uModDate "Unix seconds date last update"
//tConfig
#define LANG_FL_tConfig_uConfig "uConfig"
#define LANG_FT_tConfig_uConfig "Primary Key"
#define LANG_FL_tConfig_cLabel "cLabel"
#define LANG_FT_tConfig_cLabel "Short label"
#define LANG_FL_tConfig_uOwner "uOwner"
#define LANG_FT_tConfig_uOwner "Record owner"
#define LANG_FL_tConfig_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfig_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfig_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfig_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfig_uModBy "uModBy"
#define LANG_FT_tConfig_uModBy "uClient for last update"
#define LANG_FL_tConfig_uModDate "uModDate"
#define LANG_FT_tConfig_uModDate "Unix seconds date last update"
//tIP
#define LANG_FL_tIP_uIP "uIP"
#define LANG_FT_tIP_uIP "Primary Key"
#define LANG_FL_tIP_cLabel "cLabel"
#define LANG_FT_tIP_cLabel "Short label"
#define LANG_FL_tIP_uAvailable "uAvailable"
#define LANG_FT_tIP_uAvailable "IP is available for use"
#define LANG_FL_tIP_uOwner "uOwner"
#define LANG_FT_tIP_uOwner "Record owner"
#define LANG_FL_tIP_uCreatedBy "uCreatedBy"
#define LANG_FT_tIP_uCreatedBy "uClient for last insert"
#define LANG_FL_tIP_uCreatedDate "uCreatedDate"
#define LANG_FT_tIP_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tIP_uModBy "uModBy"
#define LANG_FT_tIP_uModBy "uClient for last update"
#define LANG_FL_tIP_uModDate "uModDate"
#define LANG_FT_tIP_uModDate "Unix seconds date last update"
//tGroupType
#define LANG_FL_tGroupType_uGroupType "uGroupType"
#define LANG_FT_tGroupType_uGroupType "Primary Key"
#define LANG_FL_tGroupType_cLabel "cLabel"
#define LANG_FT_tGroupType_cLabel "Short label"
#define LANG_FL_tGroupType_uOwner "uOwner"
#define LANG_FT_tGroupType_uOwner "Record owner"
#define LANG_FL_tGroupType_uCreatedBy "uCreatedBy"
#define LANG_FT_tGroupType_uCreatedBy "uClient for last insert"
#define LANG_FL_tGroupType_uCreatedDate "uCreatedDate"
#define LANG_FT_tGroupType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGroupType_uModBy "uModBy"
#define LANG_FT_tGroupType_uModBy "uClient for last update"
#define LANG_FL_tGroupType_uModDate "uModDate"
#define LANG_FT_tGroupType_uModDate "Unix seconds date last update"
//tGroup
#define LANG_FL_tGroup_uGroup "uGroup"
#define LANG_FT_tGroup_uGroup "Primary Key"
#define LANG_FL_tGroup_cLabel "cLabel"
#define LANG_FT_tGroup_cLabel "Short label"
#define LANG_FL_tGroup_uGroupType "uGroupType"
#define LANG_FT_tGroup_uGroupType "Group type association"
#define LANG_FL_tGroup_uOwner "uOwner"
#define LANG_FT_tGroup_uOwner "Record owner"
#define LANG_FL_tGroup_uCreatedBy "uCreatedBy"
#define LANG_FT_tGroup_uCreatedBy "uClient for last insert"
#define LANG_FL_tGroup_uCreatedDate "uCreatedDate"
#define LANG_FT_tGroup_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGroup_uModBy "uModBy"
#define LANG_FT_tGroup_uModBy "uClient for last update"
#define LANG_FL_tGroup_uModDate "uModDate"
#define LANG_FT_tGroup_uModDate "Unix seconds date last update"
//tGroupGlue
#define LANG_FL_tGroupGlue_uGroupGlue "uGroupGlue"
#define LANG_FT_tGroupGlue_uGroupGlue "Primary Key"
#define LANG_FL_tGroupGlue_uGroup "uGroup"
#define LANG_FT_tGroupGlue_uGroup "Glue into tGroup"
#define LANG_FL_tGroupGlue_uNode "uNode"
#define LANG_FT_tGroupGlue_uNode "Glue into tNode"
#define LANG_FL_tGroupGlue_uContainer "uContainer"
#define LANG_FT_tGroupGlue_uContainer "Glue into tContainer"
//tClient
//tTemplate
//tTemplateSet
//tTemplateType
//tLog
//tLogType
//tLogMonth
//tGlossary
//tJob
//tJobStatus
//tStatus
//tConfiguration
