// svn ID removed
// English: USA
// Navigation bar buttons and results

#define LANG_NB_LIST "List"
#define LANG_NB_MODIFY "Modify"
#define LANG_NB_CONFIRMMOD "Confirm Modify"
#define LANG_NB_NEW "New"
#define LANG_NB_DELETE "Delete"
#define LANG_NB_CONFIRMNEW "Create New Record"
#define LANG_NBB_CONFIRMNEW "<input class=lrevButton title='Double check!' type=submit name=gcCommand value=\"Create New Record\">"
#define LANG_NB_CONFIRMDEL "Confirm Delete"
#define LANG_NBB_CONFIRMDEL "<input class=lwarnButton title='No undo available!' type=submit name=gcCommand value=\"Confirm Delete\">"
#define LANG_NBB_CONFIRMMOD "<input class=lalertButton title='Double check!' type=submit name=gcCommand value=\"Confirm Modify\">"


#define LANG_NBR_FOUND " Found"
#define LANG_NBR_MODIFIED " Modified"
#define LANG_NBR_NEW " New"
#define LANG_NBR_NORECS " No records found"
#define LANG_NBRF_SHOWING " (Showing %lu of %d)"

#define LANG_NBR_RECEXISTS "<blink>Record already exists"
#define LANG_NBR_NEWRECADDED "New record %u added"
#define LANG_NBR_RECDELETED "Record Deleted"
#define LANG_NBR_RECNOTDELETED "Record Not Deleted"
#define LANG_NBR_RECNOTEXIST "<blink>Record does not exist"
#define LANG_NBR_MULTRECS "<blink>Multiple rows!"
#define LANG_NBR_EXTMOD "<blink>This record was just modified by another user!"
#define LANG_NBRF_REC_MODIFIED "record %s modified"

#define LANG_NBB_SKIPFIRST "<input style='width:30px;' title=\"Skip to first record\" type=submit name=gcFind value=\"<<\" >"
#define LANG_NBB_SKIPBACK "<input style='width:30px;' title=\"Go back one record\" type=submit name=gcFind value=\"< \" >"
#define LANG_NBB_SKIPNEXT "<input style='width:30px;' title=\"Advance to next record\" type=submit name=gcFind value=\" >\" >"
#define LANG_NBB_SKIPLAST "<input style='width:30px;' title=\"Skip to last record\" type=submit name=gcFind value=\">>\" >\n"

//Modified for local .h use
#define LANG_NBB_NEWREV "<input class=revButton title=\"Create new record\" type=submit name=gcCommand value=New>"
#define LANG_NBB_NEW "<input  title=\"Create new record\" type=submit name=gcCommand value=New>"
#define LANG_NBB_DELETE "<input class=warnButton title=\"Delete current record\" type=submit name=gcCommand value=Delete>"
#define LANG_NBB_MODIFY "<input class=alertButton title=\"Modify current record\" type=submit name=gcCommand value=Modify>"

#define LANG_NBB_LIST "<input title=\"Paginated listing of all records\" type=submit name=gcFind value=List>"
#define LANG_NBB_SEARCH "<input class=revButton title=\"Find record with parameters set below\" type=submit name=gcFind value=Search>"

#define LANG_PAGEMACHINE_HINT "No matching records found.<br>"
#define LANG_PAGEMACHINE_SHOWING "Page %d/%d (Records %d-%d of %d)\n"
#define LANG_PAGEMACHINE_SEARCH "<input type=submit name=gcFind value=Search >"
#define LANG_PAGEMACHINE_SEARCHBUTTON "Search"

//tTemplate
#define LANG_FL_tTemplate_uTemplate "uTemplate"
#define LANG_FT_tTemplate_uTemplate "Primary Key"
#define LANG_FL_tTemplate_cLabel "cLabel"
#define LANG_FT_tTemplate_cLabel "Short label"
#define LANG_FL_tTemplate_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplate_uTemplateSet "Short label"
#define LANG_FL_tTemplate_uTemplateType "uTemplateType"
#define LANG_FT_tTemplate_uTemplateType "Short label"
#define LANG_FL_tTemplate_cComment "cComment"
#define LANG_FT_tTemplate_cComment "About the template"
#define LANG_FL_tTemplate_cTemplate "cTemplate"
#define LANG_FT_tTemplate_cTemplate "Template itself"
#define LANG_FL_tTemplate_uOwner "uOwner"
#define LANG_FT_tTemplate_uOwner "Record owner"
#define LANG_FL_tTemplate_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplate_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplate_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplate_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplate_uModBy "uModBy"
#define LANG_FT_tTemplate_uModBy "uClient for last update"
#define LANG_FL_tTemplate_uModDate "uModDate"
#define LANG_FT_tTemplate_uModDate "Unix seconds date last update"
//tTemplateSet
#define LANG_FL_tTemplateSet_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplateSet_uTemplateSet "Primary Key"
#define LANG_FL_tTemplateSet_cLabel "cLabel"
#define LANG_FT_tTemplateSet_cLabel "Short label"
#define LANG_FL_tTemplateSet_uOwner "uOwner"
#define LANG_FT_tTemplateSet_uOwner "Record owner"
#define LANG_FL_tTemplateSet_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateSet_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateSet_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateSet_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateSet_uModBy "uModBy"
#define LANG_FT_tTemplateSet_uModBy "uClient for last update"
#define LANG_FL_tTemplateSet_uModDate "uModDate"
#define LANG_FT_tTemplateSet_uModDate "Unix seconds date last update"
//tTemplateType
#define LANG_FL_tTemplateType_uTemplateType "uTemplateType"
#define LANG_FT_tTemplateType_uTemplateType "Primary Key"
#define LANG_FL_tTemplateType_cLabel "cLabel"
#define LANG_FT_tTemplateType_cLabel "Short label"
#define LANG_FL_tTemplateType_uOwner "uOwner"
#define LANG_FT_tTemplateType_uOwner "Record owner"
#define LANG_FL_tTemplateType_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateType_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateType_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateType_uModBy "uModBy"
#define LANG_FT_tTemplateType_uModBy "uClient for last update"
#define LANG_FL_tTemplateType_uModDate "uModDate"
#define LANG_FT_tTemplateType_uModDate "Unix seconds date last update"
//tConfiguration
#define LANG_FL_tConfiguration_uConfiguration "uConfiguration"
#define LANG_FT_tConfiguration_uConfiguration "Primary Key"
#define LANG_FL_tConfiguration_uServer "uServer"
#define LANG_FT_tConfiguration_uServer "uServer"
#define LANG_FL_tConfiguration_cLabel "cLabel"
#define LANG_FT_tConfiguration_cLabel "cLabel is Name of Name/Value Pair"
#define LANG_FL_tConfiguration_cValue "cValue"
#define LANG_FT_tConfiguration_cValue "Value of name(cLabel)/value pair"
#define LANG_FL_tConfiguration_cComment "cComment"
#define LANG_FT_tConfiguration_cComment "Comment about this configuration name/value pair"
#define LANG_FL_tConfiguration_uOwner "uOwner"
#define LANG_FT_tConfiguration_uOwner "Record owner"
#define LANG_FL_tConfiguration_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfiguration_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfiguration_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfiguration_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfiguration_uModBy "uModBy"
#define LANG_FT_tConfiguration_uModBy "uClient for last update"
#define LANG_FL_tConfiguration_uModDate "uModDate"
#define LANG_FT_tConfiguration_uModDate "Unix seconds date last update"
//tLog
#define LANG_FL_tLog_uLog "uLog"
#define LANG_FT_tLog_uLog "Primary Key"
#define LANG_FL_tLog_cLabel "cLabel"
#define LANG_FT_tLog_cLabel "Short label"
#define LANG_FL_tLog_uLogType "uLogType"
#define LANG_FT_tLog_uLogType "Log Type"
#define LANG_FL_tLog_cHash "cHash"
#define LANG_FT_tLog_cHash "Security hash to complicate tampering"
#define LANG_FL_tLog_uPermLevel "uPermLevel"
#define LANG_FT_tLog_uPermLevel "User Perm Level"
#define LANG_FL_tLog_uLoginClient "uLoginClient"
#define LANG_FT_tLog_uLoginClient "Client Number"
#define LANG_FL_tLog_cLogin "cLogin"
#define LANG_FT_tLog_cLogin "Login name"
#define LANG_FL_tLog_cHost "cHost"
#define LANG_FT_tLog_cHost "Ip Address"
#define LANG_FL_tLog_uTablePK "uTablePK"
#define LANG_FT_tLog_uTablePK "Primar Key of the Table"
#define LANG_FL_tLog_cTableName "cTableName"
#define LANG_FT_tLog_cTableName "Name of the Table"
#define LANG_FL_tLog_cMessage "cMessage"
#define LANG_FT_tLog_cMessage "Message text"
#define LANG_FL_tLog_cServer "cServer"
#define LANG_FT_tLog_cServer "Server name"
#define LANG_FL_tLog_uOwner "uOwner"
#define LANG_FT_tLog_uOwner "Record owner"
#define LANG_FL_tLog_uCreatedBy "uCreatedBy"
#define LANG_FT_tLog_uCreatedBy "uClient for last insert"
#define LANG_FL_tLog_uCreatedDate "uCreatedDate"
#define LANG_FT_tLog_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLog_uModBy "uModBy"
#define LANG_FT_tLog_uModBy "uClient for last update"
#define LANG_FL_tLog_uModDate "uModDate"
#define LANG_FT_tLog_uModDate "Unix seconds date last update"
//tLogType
#define LANG_FL_tLogType_uLogType "uLogType"
#define LANG_FT_tLogType_uLogType "Primary Key"
#define LANG_FL_tLogType_cLabel "cLabel"
#define LANG_FT_tLogType_cLabel "Short label"
#define LANG_FL_tLogType_uOwner "uOwner"
#define LANG_FT_tLogType_uOwner "Record owner"
#define LANG_FL_tLogType_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogType_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogType_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogType_uModBy "uModBy"
#define LANG_FT_tLogType_uModBy "uClient for last update"
#define LANG_FL_tLogType_uModDate "uModDate"
#define LANG_FT_tLogType_uModDate "Unix seconds date last update"
//tLogMonth
#define LANG_FL_tLogMonth_uLog "uLog"
#define LANG_FT_tLogMonth_uLog "Primary Key"
#define LANG_FL_tLogMonth_cLabel "cLabel"
#define LANG_FT_tLogMonth_cLabel "Short label"
#define LANG_FL_tLogMonth_uLogType "uLogType"
#define LANG_FT_tLogMonth_uLogType "Log Type"
#define LANG_FL_tLogMonth_cHash "cHash"
#define LANG_FT_tLogMonth_cHash "Security hash to complicate tampering"
#define LANG_FL_tLogMonth_uPermLevel "uPermLevel"
#define LANG_FT_tLogMonth_uPermLevel "User Perm Level"
#define LANG_FL_tLogMonth_uLoginClient "uLoginClient"
#define LANG_FT_tLogMonth_uLoginClient "Client Number"
#define LANG_FL_tLogMonth_cLogin "cLogin"
#define LANG_FT_tLogMonth_cLogin "Login name"
#define LANG_FL_tLogMonth_cHost "cHost"
#define LANG_FT_tLogMonth_cHost "Ip Address"
#define LANG_FL_tLogMonth_uTablePK "uTablePK"
#define LANG_FT_tLogMonth_uTablePK "Primar Key of the Table"
#define LANG_FL_tLogMonth_cTableName "cTableName"
#define LANG_FT_tLogMonth_cTableName "Name of the Table"
#define LANG_FL_tLogMonth_uOwner "uOwner"
#define LANG_FT_tLogMonth_uOwner "Record owner"
#define LANG_FL_tLogMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogMonth_uModBy "uModBy"
#define LANG_FT_tLogMonth_uModBy "uClient for last update"
#define LANG_FL_tLogMonth_uModDate "uModDate"
#define LANG_FT_tLogMonth_uModDate "Unix seconds date last update"
//tClient
#define LANG_FL_tClient_uClient "uClient"
#define LANG_FT_tClient_uClient "Primary Key"
#define LANG_FL_tClient_cLabel "cLabel"
#define LANG_FT_tClient_cLabel "Short label"
#define LANG_FL_tClient_cInfo "cInfo"
#define LANG_FT_tClient_cInfo "Unformatted info/address etc."
#define LANG_FL_tClient_cEmail "cEmail"
#define LANG_FT_tClient_cEmail "Main Email"
#define LANG_FL_tClient_cCode "cCode"
#define LANG_FT_tClient_cCode "Enterprise wide customer/contact tracking"
#define LANG_FL_tClient_uOwner "uOwner"
#define LANG_FT_tClient_uOwner "Record owner"
#define LANG_FL_tClient_uCreatedBy "uCreatedBy"
#define LANG_FT_tClient_uCreatedBy "uClient for last insert"
#define LANG_FL_tClient_uCreatedDate "uCreatedDate"
#define LANG_FT_tClient_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tClient_uModBy "uModBy"
#define LANG_FT_tClient_uModBy "uClient for last update"
#define LANG_FL_tClient_uModDate "uModDate"
#define LANG_FT_tClient_uModDate "Unix seconds date last update"
//tAuthorize
#define LANG_FL_tAuthorize_uAuthorize "uAuthorize"
#define LANG_FT_tAuthorize_uAuthorize "Primary Key"
#define LANG_FL_tAuthorize_cLabel "cLabel"
#define LANG_FT_tAuthorize_cLabel "Short label"
#define LANG_FL_tAuthorize_cIpMask "cIpMask"
#define LANG_FT_tAuthorize_cIpMask "Allow user from this IP"
#define LANG_FL_tAuthorize_uPerm "uPerm"
#define LANG_FT_tAuthorize_uPerm "User permission level"
#define LANG_FL_tAuthorize_uCertClient "uCertClient"
#define LANG_FT_tAuthorize_uCertClient "User uClient"
#define LANG_FL_tAuthorize_cPasswd "cPasswd"
#define LANG_FT_tAuthorize_cPasswd "Encrypted cgi login password"
#define LANG_FL_tAuthorize_cClrPasswd "cClrPasswd"
#define LANG_FT_tAuthorize_cClrPasswd "Optionally used non encrypted login password"
#define LANG_FL_tAuthorize_uOwner "uOwner"
#define LANG_FT_tAuthorize_uOwner "Record owner"
#define LANG_FL_tAuthorize_uCreatedBy "uCreatedBy"
#define LANG_FT_tAuthorize_uCreatedBy "uClient for last insert"
#define LANG_FL_tAuthorize_uCreatedDate "uCreatedDate"
#define LANG_FT_tAuthorize_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tAuthorize_uModBy "uModBy"
#define LANG_FT_tAuthorize_uModBy "uClient for last update"
#define LANG_FL_tAuthorize_uModDate "uModDate"
#define LANG_FT_tAuthorize_uModDate "Unix seconds date last update"
//tMonth
#define LANG_FL_tMonth_uMonth "uMonth"
#define LANG_FT_tMonth_uMonth "Primary Key"
#define LANG_FL_tMonth_cLabel "cLabel"
#define LANG_FT_tMonth_cLabel "Name of Archive Table Ex. tNov2009"
#define LANG_FL_tMonth_uOwner "uOwner"
#define LANG_FT_tMonth_uOwner "Record owner"
#define LANG_FL_tMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tMonth_uModBy "uModBy"
#define LANG_FT_tMonth_uModBy "uClient for last update"
#define LANG_FL_tMonth_uModDate "uModDate"
#define LANG_FT_tMonth_uModDate "Unix seconds date last update"
//tGlossary
#define LANG_FL_tGlossary_uGlossary "uGlossary"
#define LANG_FT_tGlossary_uGlossary "Primary Key"
#define LANG_FL_tGlossary_cLabel "cLabel"
#define LANG_FT_tGlossary_cLabel "Short label"
#define LANG_FL_tGlossary_cText "cText"
#define LANG_FT_tGlossary_cText "Definition of the label referenced in cLabel"
#define LANG_FL_tGlossary_uOwner "uOwner"
#define LANG_FT_tGlossary_uOwner "Record owner"
#define LANG_FL_tGlossary_uCreatedBy "uCreatedBy"
#define LANG_FT_tGlossary_uCreatedBy "uClient for last insert"
#define LANG_FL_tGlossary_uCreatedDate "uCreatedDate"
#define LANG_FT_tGlossary_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGlossary_uModBy "uModBy"
#define LANG_FT_tGlossary_uModBy "uClient for last update"
#define LANG_FL_tGlossary_uModDate "uModDate"
#define LANG_FT_tGlossary_uModDate "Unix seconds date last update"
//tJob
#define LANG_FL_tJob_uJob "uJob"
#define LANG_FT_tJob_uJob "Primary Key"
#define LANG_FL_tJob_cLabel "cLabel"
#define LANG_FT_tJob_cLabel "Label for user feedback"
#define LANG_FL_tJob_cServer "cServer"
#define LANG_FT_tJob_cServer "Server name ip or any server"
#define LANG_FL_tJob_cJobName "cJobName"
#define LANG_FT_tJob_cJobName "Subsystem.Function style job name"
#define LANG_FL_tJob_uJobTarget "uJobTarget"
#define LANG_FT_tJob_uJobTarget "Owner of resources created/mod"
#define LANG_FL_tJob_uJobTargetUser "uJobTargetUser"
#define LANG_FT_tJob_uJobTargetUser "Target User ID"
#define LANG_FL_tJob_cJobData "cJobData"
#define LANG_FT_tJob_cJobData "Remote subsystem server function arguments"
#define LANG_FL_tJob_uJobDate "uJobDate"
#define LANG_FT_tJob_uJobDate "Unix seconds for job to start to be considered"
#define LANG_FL_tJob_uJobStatus "uJobStatus"
#define LANG_FT_tJob_uJobStatus "Waiting, being processed, done, error"
#define LANG_FL_tJob_cRemoteMsg "cRemoteMsg"
#define LANG_FT_tJob_cRemoteMsg "Remote subsytem error message"
#define LANG_FL_tJob_uOwner "uOwner"
#define LANG_FT_tJob_uOwner "Record owner"
#define LANG_FL_tJob_uCreatedBy "uCreatedBy"
#define LANG_FT_tJob_uCreatedBy "uClient for last insert"
#define LANG_FL_tJob_uCreatedDate "uCreatedDate"
#define LANG_FT_tJob_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJob_uModBy "uModBy"
#define LANG_FT_tJob_uModBy "uClient for last update"
#define LANG_FL_tJob_uModDate "uModDate"
#define LANG_FT_tJob_uModDate "Unix seconds date last update"
//tServer
#define LANG_FL_tServer_uServer "uServer"
#define LANG_FT_tServer_uServer "Primary Key"
#define LANG_FL_tServer_cLabel "cLabel"
#define LANG_FT_tServer_cLabel "Short label"
#define LANG_FL_tServer_uOwner "uOwner"
#define LANG_FT_tServer_uOwner "Record owner"
#define LANG_FL_tServer_uCreatedBy "uCreatedBy"
#define LANG_FT_tServer_uCreatedBy "uClient for last insert"
#define LANG_FL_tServer_uCreatedDate "uCreatedDate"
#define LANG_FT_tServer_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tServer_uModBy "uModBy"
#define LANG_FT_tServer_uModBy "uClient for last update"
#define LANG_FL_tServer_uModDate "uModDate"
#define LANG_FT_tServer_uModDate "Unix seconds date last update"
//tJobStatus
#define LANG_FL_tJobStatus_uJobStatus "uJobStatus"
#define LANG_FT_tJobStatus_uJobStatus "Primary Key"
#define LANG_FL_tJobStatus_cLabel "cLabel"
#define LANG_FT_tJobStatus_cLabel "Short label"
#define LANG_FL_tJobStatus_uOwner "uOwner"
#define LANG_FT_tJobStatus_uOwner "Record owner"
#define LANG_FL_tJobStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tJobStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tJobStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tJobStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJobStatus_uModBy "uModBy"
#define LANG_FT_tJobStatus_uModBy "uClient for last update"
#define LANG_FL_tJobStatus_uModDate "uModDate"
#define LANG_FT_tJobStatus_uModDate "Unix seconds date last update"
//tStatus
#define LANG_FL_tStatus_uStatus "uStatus"
#define LANG_FT_tStatus_uStatus "Primary Key"
#define LANG_FL_tStatus_cLabel "cLabel"
#define LANG_FT_tStatus_cLabel "Short label"
#define LANG_FL_tStatus_uOwner "uOwner"
#define LANG_FT_tStatus_uOwner "Record owner"
#define LANG_FL_tStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tStatus_uModBy "uModBy"
#define LANG_FT_tStatus_uModBy "uClient for last update"
#define LANG_FL_tStatus_uModDate "uModDate"
#define LANG_FT_tStatus_uModDate "Unix seconds date last update"
//tUser
#define LANG_FL_tUser_uUser "uUser"
#define LANG_FT_tUser_uUser "Primary Key"
#define LANG_FL_tUser_cLogin "cLogin"
#define LANG_FT_tUser_cLogin "Pop3 user login"
#define LANG_FL_tUser_uDomain "uDomain"
#define LANG_FT_tUser_uDomain "Domain if applicable"
#define LANG_FL_tUser_cPasswd "cPasswd"
#define LANG_FT_tUser_cPasswd "User passwd"
#define LANG_FL_tUser_uUserType "uUserType"
#define LANG_FT_tUser_uUserType "General user type"
#define LANG_FL_tUser_uServerGroup "uServerGroup"
#define LANG_FT_tUser_uServerGroup "Server group account is on"
#define LANG_FL_tUser_uStatus "uStatus"
#define LANG_FT_tUser_uStatus "Status of user"
#define LANG_FL_tUser_cSecretQuestion "cSecretQuestion"
#define LANG_FT_tUser_cSecretQuestion "Security question for password update"
#define LANG_FL_tUser_cSecretAnswer "cSecretAnswer"
#define LANG_FT_tUser_cSecretAnswer "Security question answer for password update"
#define LANG_FL_tUser_uClient "uClient"
#define LANG_FL_tUser_uOwner "uOwner"
#define LANG_FT_tUser_uOwner "Record owner"
#define LANG_FL_tUser_uCreatedBy "uCreatedBy"
#define LANG_FT_tUser_uCreatedBy "uClient for last insert"
#define LANG_FL_tUser_uCreatedDate "uCreatedDate"
#define LANG_FT_tUser_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tUser_uModBy "uModBy"
#define LANG_FT_tUser_uModBy "uClient for last update"
#define LANG_FL_tUser_uModDate "uModDate"
#define LANG_FT_tUser_uModDate "Unix seconds date last update"
//tAlias
#define LANG_FL_tAlias_uAlias "uAlias"
#define LANG_FT_tAlias_uAlias "Primary Key"
#define LANG_FL_tAlias_cUser "cUser"
#define LANG_FT_tAlias_cUser "Local mail user"
#define LANG_FL_tAlias_cTargetEmail "cTargetEmail"
#define LANG_FT_tAlias_cTargetEmail "Local mail user destination email or program"
#define LANG_FL_tAlias_uServerGroup "uServerGroup"
#define LANG_FT_tAlias_uServerGroup "Servers account is on"
#define LANG_FL_tAlias_uOwner "uOwner"
#define LANG_FT_tAlias_uOwner "Record owner"
#define LANG_FL_tAlias_uCreatedBy "uCreatedBy"
#define LANG_FT_tAlias_uCreatedBy "uClient for last insert"
#define LANG_FL_tAlias_uCreatedDate "uCreatedDate"
#define LANG_FT_tAlias_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tAlias_uModBy "uModBy"
#define LANG_FT_tAlias_uModBy "uClient for last update"
#define LANG_FL_tAlias_uModDate "uModDate"
#define LANG_FT_tAlias_uModDate "Unix seconds date last update"
//tDomain
#define LANG_FL_tDomain_uDomain "uDomain"
#define LANG_FT_tDomain_uDomain "Primary Key"
#define LANG_FL_tDomain_cDomain "cDomain"
#define LANG_FT_tDomain_cDomain "FQ Domain Name"
#define LANG_FL_tDomain_uOwner "uOwner"
#define LANG_FT_tDomain_uOwner "Record owner"
#define LANG_FL_tDomain_uCreatedBy "uCreatedBy"
#define LANG_FT_tDomain_uCreatedBy "uClient for last insert"
#define LANG_FL_tDomain_uCreatedDate "uCreatedDate"
#define LANG_FT_tDomain_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tDomain_uModBy "uModBy"
#define LANG_FT_tDomain_uModBy "uClient for last update"
#define LANG_FL_tDomain_uModDate "uModDate"
#define LANG_FT_tDomain_uModDate "Unix seconds date last update"
//tVUT
#define LANG_FL_tVUT_uVUT "uVUT"
#define LANG_FT_tVUT_uVUT "Primary Key"
#define LANG_FL_tVUT_cDomain "cDomain"
#define LANG_FT_tVUT_cDomain "FQ Domain Name"
#define LANG_FL_tVUT_uServerGroup "uServerGroup"
#define LANG_FT_tVUT_uServerGroup "Server group account is on"
#define LANG_FL_tVUT_uOwner "uOwner"
#define LANG_FT_tVUT_uOwner "Record owner"
#define LANG_FL_tVUT_uCreatedBy "uCreatedBy"
#define LANG_FT_tVUT_uCreatedBy "uClient for last insert"
#define LANG_FL_tVUT_uCreatedDate "uCreatedDate"
#define LANG_FT_tVUT_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tVUT_uModBy "uModBy"
#define LANG_FT_tVUT_uModBy "uClient for last update"
#define LANG_FL_tVUT_uModDate "uModDate"
#define LANG_FT_tVUT_uModDate "Unix seconds date last update"
//tVUTEntries
#define LANG_FL_tVUTEntries_uVUTEntries "uVUTEntries"
#define LANG_FT_tVUTEntries_uVUTEntries "Primary Key"
#define LANG_FL_tVUTEntries_uVUT "uVUT"
#define LANG_FT_tVUTEntries_uVUT "VUT domain"
#define LANG_FL_tVUTEntries_cVirtualEmail "cVirtualEmail"
#define LANG_FT_tVUTEntries_cVirtualEmail "Virtual email address no @FQDN"
#define LANG_FL_tVUTEntries_cTargetEmail "cTargetEmail"
#define LANG_FT_tVUTEntries_cTargetEmail "Target email address with @FQDN"
#define LANG_FL_tVUTEntries_uOwner "uOwner"
#define LANG_FT_tVUTEntries_uOwner "Record owner"
#define LANG_FL_tVUTEntries_uCreatedBy "uCreatedBy"
#define LANG_FT_tVUTEntries_uCreatedBy "uClient for last insert"
#define LANG_FL_tVUTEntries_uCreatedDate "uCreatedDate"
#define LANG_FT_tVUTEntries_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tVUTEntries_uModBy "uModBy"
#define LANG_FT_tVUTEntries_uModBy "uClient for last update"
#define LANG_FL_tVUTEntries_uModDate "uModDate"
#define LANG_FT_tVUTEntries_uModDate "Unix seconds date last update"
//tAccess
#define LANG_FL_tAccess_uAccess "uAccess"
#define LANG_FT_tAccess_uAccess "Primary Key"
#define LANG_FL_tAccess_cDomainIP "cDomainIP"
#define LANG_FT_tAccess_cDomainIP "Domain or IP (Class C, class B of full IP)"
#define LANG_FL_tAccess_cRelayAttr "cRelayAttr"
#define LANG_FT_tAccess_cRelayAttr "Allow, reject or other error message"
#define LANG_FL_tAccess_uServerGroup "uServerGroup"
#define LANG_FT_tAccess_uServerGroup "Server group account is on"
#define LANG_FL_tAccess_uExpireDate "uExpireDate"
#define LANG_FT_tAccess_uExpireDate "Expire this tAccess entry at this time"
#define LANG_FL_tAccess_uSource "uSource"
#define LANG_FT_tAccess_uSource "Where this record came from"
#define LANG_FL_tAccess_uOwner "uOwner"
#define LANG_FT_tAccess_uOwner "Record owner"
#define LANG_FL_tAccess_uCreatedBy "uCreatedBy"
#define LANG_FT_tAccess_uCreatedBy "uClient for last insert"
#define LANG_FL_tAccess_uCreatedDate "uCreatedDate"
#define LANG_FT_tAccess_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tAccess_uModBy "uModBy"
#define LANG_FT_tAccess_uModBy "uClient for last update"
#define LANG_FL_tAccess_uModDate "uModDate"
#define LANG_FT_tAccess_uModDate "Unix seconds date last update"
//tRelay
#define LANG_FL_tRelay_uRelay "uRelay"
#define LANG_FT_tRelay_uRelay "Primary Key"
#define LANG_FL_tRelay_cDomain "cDomain"
#define LANG_FT_tRelay_cDomain "Domain name"
#define LANG_FL_tRelay_cTransport "cTransport"
#define LANG_FT_tRelay_cTransport "Mail Transport"
#define LANG_FL_tRelay_uServerGroup "uServerGroup"
#define LANG_FT_tRelay_uServerGroup "Server group account is on"
#define LANG_FL_tRelay_uOwner "uOwner"
#define LANG_FT_tRelay_uOwner "Record owner"
#define LANG_FL_tRelay_uCreatedBy "uCreatedBy"
#define LANG_FT_tRelay_uCreatedBy "uClient for last insert"
#define LANG_FL_tRelay_uCreatedDate "uCreatedDate"
#define LANG_FT_tRelay_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tRelay_uModBy "uModBy"
#define LANG_FT_tRelay_uModBy "uClient for last update"
#define LANG_FL_tRelay_uModDate "uModDate"
#define LANG_FT_tRelay_uModDate "Unix seconds date last update"
//tLocal
#define LANG_FL_tLocal_uLocal "uLocal"
#define LANG_FT_tLocal_uLocal "Primary Key"
#define LANG_FL_tLocal_cDomain "cDomain"
#define LANG_FT_tLocal_cDomain "Domain for local mail delivery"
#define LANG_FL_tLocal_uServerGroup "uServerGroup"
#define LANG_FT_tLocal_uServerGroup "Server group account is on"
#define LANG_FL_tLocal_uOwner "uOwner"
#define LANG_FT_tLocal_uOwner "Record owner"
#define LANG_FL_tLocal_uCreatedBy "uCreatedBy"
#define LANG_FT_tLocal_uCreatedBy "uClient for last insert"
#define LANG_FL_tLocal_uCreatedDate "uCreatedDate"
#define LANG_FT_tLocal_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLocal_uModBy "uModBy"
#define LANG_FT_tLocal_uModBy "uClient for last update"
#define LANG_FL_tLocal_uModDate "uModDate"
#define LANG_FT_tLocal_uModDate "Unix seconds date last update"
//tUserType
#define LANG_FL_tUserType_uUserType "uUserType"
#define LANG_FT_tUserType_uUserType "Primary Key"
#define LANG_FL_tUserType_cLabel "cLabel"
#define LANG_FT_tUserType_cLabel "Short label"
#define LANG_FL_tUserType_uOwner "uOwner"
#define LANG_FT_tUserType_uOwner "Record owner"
#define LANG_FL_tUserType_uCreatedBy "uCreatedBy"
#define LANG_FT_tUserType_uCreatedBy "uClient for last insert"
#define LANG_FL_tUserType_uCreatedDate "uCreatedDate"
#define LANG_FT_tUserType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tUserType_uModBy "uModBy"
#define LANG_FT_tUserType_uModBy "uClient for last update"
#define LANG_FL_tUserType_uModDate "uModDate"
#define LANG_FT_tUserType_uModDate "Unix seconds date last update"
//tUserConfig
#define LANG_FL_tUserConfig_uUserConfig "uUserConfig"
#define LANG_FT_tUserConfig_uUserConfig "Primary Key"
#define LANG_FL_tUserConfig_cLabel "cLabel"
#define LANG_FT_tUserConfig_cLabel "Short label"
#define LANG_FL_tUserConfig_uUser "uUser"
#define LANG_FT_tUserConfig_uUser "tUser.uUser"
#define LANG_FL_tUserConfig_uConfigSpec "uConfigSpec"
#define LANG_FT_tUserConfig_uConfigSpec "Index into tConfigSpec"
#define LANG_FL_tUserConfig_cConfig "cConfig"
#define LANG_FT_tUserConfig_cConfig "Configuration file or section"
#define LANG_FL_tUserConfig_uOwner "uOwner"
#define LANG_FT_tUserConfig_uOwner "Record owner"
#define LANG_FL_tUserConfig_uCreatedBy "uCreatedBy"
#define LANG_FT_tUserConfig_uCreatedBy "uClient for last insert"
#define LANG_FL_tUserConfig_uCreatedDate "uCreatedDate"
#define LANG_FT_tUserConfig_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tUserConfig_uModBy "uModBy"
#define LANG_FT_tUserConfig_uModBy "uClient for last update"
#define LANG_FL_tUserConfig_uModDate "uModDate"
#define LANG_FT_tUserConfig_uModDate "Unix seconds date last update"
//tServerConfig
#define LANG_FL_tServerConfig_uServerConfig "uServerConfig"
#define LANG_FT_tServerConfig_uServerConfig "Primary Key"
#define LANG_FL_tServerConfig_cLabel "cLabel"
#define LANG_FT_tServerConfig_cLabel "Short label"
#define LANG_FL_tServerConfig_uServerGroup "uServerGroup"
#define LANG_FT_tServerConfig_uServerGroup "tServerGroup.uServerGroup"
#define LANG_FL_tServerConfig_uConfigSpec "uConfigSpec"
#define LANG_FT_tServerConfig_uConfigSpec "Index into tConfigSpec"
#define LANG_FL_tServerConfig_cConfig "cConfig"
#define LANG_FT_tServerConfig_cConfig "Configuration file or section"
#define LANG_FL_tServerConfig_uOwner "uOwner"
#define LANG_FT_tServerConfig_uOwner "Record owner"
#define LANG_FL_tServerConfig_uCreatedBy "uCreatedBy"
#define LANG_FT_tServerConfig_uCreatedBy "uClient for last insert"
#define LANG_FL_tServerConfig_uCreatedDate "uCreatedDate"
#define LANG_FT_tServerConfig_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tServerConfig_uModBy "uModBy"
#define LANG_FT_tServerConfig_uModBy "uClient for last update"
#define LANG_FL_tServerConfig_uModDate "uModDate"
#define LANG_FT_tServerConfig_uModDate "Unix seconds date last update"
//tConfigSpec
#define LANG_FL_tConfigSpec_uConfigSpec "uConfigSpec"
#define LANG_FT_tConfigSpec_uConfigSpec "Primary Key"
#define LANG_FL_tConfigSpec_cLabel "cLabel"
#define LANG_FT_tConfigSpec_cLabel "Short label"
#define LANG_FL_tConfigSpec_cPath "cPath"
#define LANG_FT_tConfigSpec_cPath "File path added to tConfiguration root path"
#define LANG_FL_tConfigSpec_cOwner "cOwner"
#define LANG_FT_tConfigSpec_cOwner "System file owner if applicable"
#define LANG_FL_tConfigSpec_cGroup "cGroup"
#define LANG_FT_tConfigSpec_cGroup "System file group if applicable"
#define LANG_FL_tConfigSpec_cPerms "cPerms"
#define LANG_FT_tConfigSpec_cPerms "System file chmod perms if applicable"
#define LANG_FL_tConfigSpec_cNewExec "cNewExec"
#define LANG_FT_tConfigSpec_cNewExec "System call on NewServerConfigJob()"
#define LANG_FL_tConfigSpec_cModExec "cModExec"
#define LANG_FT_tConfigSpec_cModExec "System call on ModServerConfigJob()"
#define LANG_FL_tConfigSpec_cDelExec "cDelExec"
#define LANG_FT_tConfigSpec_cDelExec "System call on DelServerConfigJob()"
#define LANG_FL_tConfigSpec_uTemplate "uTemplate"
#define LANG_FT_tConfigSpec_uTemplate "Source of downstream cConfig values"
#define LANG_FL_tConfigSpec_uOwner "uOwner"
#define LANG_FT_tConfigSpec_uOwner "Record owner"
#define LANG_FL_tConfigSpec_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfigSpec_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfigSpec_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfigSpec_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfigSpec_uModBy "uModBy"
#define LANG_FT_tConfigSpec_uModBy "uClient for last update"
#define LANG_FL_tConfigSpec_uModDate "uModDate"
#define LANG_FT_tConfigSpec_uModDate "Unix seconds date last update"
//tClient
//tAuthorize
//tStatus
#define LANG_FL_tStatus_uStatus "uStatus"
#define LANG_FT_tStatus_uStatus "Primary Key"
#define LANG_FL_tStatus_cLabel "cLabel"
#define LANG_FT_tStatus_cLabel "Short label"
#define LANG_FL_tStatus_uOwner "uOwner"
#define LANG_FT_tStatus_uOwner "Record owner"
#define LANG_FL_tStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tStatus_uModBy "uModBy"
#define LANG_FT_tStatus_uModBy "uClient for last update"
#define LANG_FL_tStatus_uModDate "uModDate"
#define LANG_FT_tStatus_uModDate "Unix seconds date last update"
//tJobStatus
#define LANG_FL_tJobStatus_uJobStatus "uJobStatus"
#define LANG_FT_tJobStatus_uJobStatus "Primary Key"
#define LANG_FL_tJobStatus_cLabel "cLabel"
#define LANG_FT_tJobStatus_cLabel "Short label"
#define LANG_FL_tJobStatus_uOwner "uOwner"
#define LANG_FT_tJobStatus_uOwner "Record owner"
#define LANG_FL_tJobStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tJobStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tJobStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tJobStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJobStatus_uModBy "uModBy"
#define LANG_FT_tJobStatus_uModBy "uClient for last update"
#define LANG_FL_tJobStatus_uModDate "uModDate"
#define LANG_FT_tJobStatus_uModDate "Unix seconds date last update"
//tTemplate
//tTemplateSet
//tTemplateType
//tLog
//tLogType
//tLogMonth
//tMonth
//tGlossary
//tJob
//tServer
//tConfiguration
//tServerGroup
#define LANG_FL_tServerGroup_uServerGroup "uServerGroup"
#define LANG_FT_tServerGroup_uServerGroup "Primary Key"
#define LANG_FL_tServerGroup_cLabel "cLabel"
#define LANG_FT_tServerGroup_cLabel "Short label"
#define LANG_FL_tServerGroup_uOwner "uOwner"
#define LANG_FT_tServerGroup_uOwner "Record owner"
#define LANG_FL_tServerGroup_uCreatedBy "uCreatedBy"
#define LANG_FT_tServerGroup_uCreatedBy "uClient for last insert"
#define LANG_FL_tServerGroup_uCreatedDate "uCreatedDate"
#define LANG_FT_tServerGroup_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tServerGroup_uModBy "uModBy"
#define LANG_FT_tServerGroup_uModBy "uClient for last update"
#define LANG_FL_tServerGroup_uModDate "uModDate"
#define LANG_FT_tServerGroup_uModDate "Unix seconds date last update"
//tServerGroupGlue
#define LANG_FL_tServerGroupGlue_uServerGroupGlue "uServerGroupGlue"
#define LANG_FT_tServerGroupGlue_uServerGroupGlue "Primary Key"
#define LANG_FL_tServerGroupGlue_uServer "uServer"
#define LANG_FT_tServerGroupGlue_uServer "tServer.uServer"
#define LANG_FL_tServerGroupGlue_uServerGroup "uServerGroup"
#define LANG_FT_tServerGroupGlue_uServerGroup "tServerGroup.uServerGroup"
//tConfiguration

//tHoldUser
#define LANG_FL_tHoldUser_uHoldUser "uHoldUser"
#define LANG_FT_tHoldUser_uHoldUser "Primary Key"
#define LANG_FL_tHoldUser_cLogin "cLogin"
#define LANG_FT_tHoldUser_cLogin "Pop3 user login"
#define LANG_FL_tHoldUser_cPasswd "cPasswd"
#define LANG_FT_tHoldUser_cPasswd "User passwd"
#define LANG_FL_tHoldUser_uUserType "uUserType"
#define LANG_FT_tHoldUser_uUserType "General user type"
#define LANG_FL_tHoldUser_uOwner "uOwner"
#define LANG_FT_tHoldUser_uOwner "Record owner"
#define LANG_FL_tHoldUser_uCreatedBy "uCreatedBy"
#define LANG_FT_tHoldUser_uCreatedBy "uClient for last insert"
#define LANG_FL_tHoldUser_uCreatedDate "uCreatedDate"
#define LANG_FT_tHoldUser_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tHoldUser_uModBy "uModBy"
#define LANG_FT_tHoldUser_uModBy "uClient for last update"
#define LANG_FL_tHoldUser_uModDate "uModDate"
#define LANG_FT_tHoldUser_uModDate "Unix seconds date last update"
//tRequest
#define LANG_FL_tRequest_uRequest "uRequest"
#define LANG_FT_tRequest_uRequest "Primary Key"
#define LANG_FL_tRequest_cId "cId"
#define LANG_FT_tRequest_cId "MD5 sum of default login"
#define LANG_FL_tRequest_cLogin "cLogin"
#define LANG_FT_tRequest_cLogin "Default login"
#define LANG_FL_tRequest_uOwner "uOwner"
#define LANG_FT_tRequest_uOwner "Record owner"
#define LANG_FL_tRequest_uCreatedBy "uCreatedBy"
#define LANG_FT_tRequest_uCreatedBy "uClient for last insert"
#define LANG_FL_tRequest_uCreatedDate "uCreatedDate"
#define LANG_FT_tRequest_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tRequest_uModBy "uModBy"
#define LANG_FT_tRequest_uModBy "uClient for last update"
#define LANG_FL_tRequest_uModDate "uModDate"
#define LANG_FT_tRequest_uModDate "Unix seconds date last update"
//tWhiteList
#define LANG_FL_tWhiteList_uWhiteList "uWhiteList"
#define LANG_FT_tWhiteList_uWhiteList "Primary Key"
#define LANG_FL_tWhiteList_cLabel "cLabel"
#define LANG_FT_tWhiteList_cLabel "Short label"
#define LANG_FL_tWhiteList_uUser "uUser"
#define LANG_FT_tWhiteList_uUser "tUser row id that requested this entry"
#define LANG_FL_tWhiteList_uServerGroup "uServerGroup"
#define LANG_FT_tWhiteList_uServerGroup "Server group the entry is at"
#define LANG_FL_tWhiteList_uOwner "uOwner"
#define LANG_FT_tWhiteList_uOwner "Record owner"
#define LANG_FL_tWhiteList_uCreatedBy "uCreatedBy"
#define LANG_FT_tWhiteList_uCreatedBy "uClient for last insert"
#define LANG_FL_tWhiteList_uCreatedDate "uCreatedDate"
#define LANG_FT_tWhiteList_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tWhiteList_uModBy "uModBy"
#define LANG_FT_tWhiteList_uModBy "uClient for last update"
#define LANG_FL_tWhiteList_uModDate "uModDate"
#define LANG_FT_tWhiteList_uModDate "Unix seconds date last update"
//tBlackList
#define LANG_FL_tBlackList_uBlackList "uBlackList"
#define LANG_FT_tBlackList_uBlackList "Primary Key"
#define LANG_FL_tBlackList_cLabel "cLabel"
#define LANG_FT_tBlackList_cLabel "Short label"
#define LANG_FL_tBlackList_uUser "uUser"
#define LANG_FT_tBlackList_uUser "tUser row id that requested this entry"
#define LANG_FL_tBlackList_uServerGroup "uServerGroup"
#define LANG_FT_tBlackList_uServerGroup "Server group the entry is at"
#define LANG_FL_tBlackList_uOwner "uOwner"
#define LANG_FT_tBlackList_uOwner "Record owner"
#define LANG_FL_tBlackList_uCreatedBy "uCreatedBy"
#define LANG_FT_tBlackList_uCreatedBy "uClient for last insert"
#define LANG_FL_tBlackList_uCreatedDate "uCreatedDate"
#define LANG_FT_tBlackList_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tBlackList_uModBy "uModBy"
#define LANG_FT_tBlackList_uModBy "uClient for last update"
#define LANG_FL_tBlackList_uModDate "uModDate"
#define LANG_FT_tBlackList_uModDate "Unix seconds date last update"
//tVacation
#define LANG_FL_tVacation_uVacation "uVacation"
#define LANG_FT_tVacation_uVacation "Primary Key"
#define LANG_FL_tVacation_uUser "uUser"
#define LANG_FT_tVacation_uUser "tUser row id"
#define LANG_FL_tVacation_uHTML "uHTML"
#define LANG_FT_tVacation_uHTML "Is html yes/no"
#define LANG_FL_tVacation_cText "cText"
#define LANG_FT_tVacation_cText "Autoreply text"
#define LANG_FL_tVacation_uOwner "uOwner"
#define LANG_FT_tVacation_uOwner "Record owner"
#define LANG_FL_tVacation_uCreatedBy "uCreatedBy"
#define LANG_FT_tVacation_uCreatedBy "uClient for last insert"
#define LANG_FL_tVacation_uCreatedDate "uCreatedDate"
#define LANG_FT_tVacation_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tVacation_uModBy "uModBy"
#define LANG_FT_tVacation_uModBy "uClient for last update"
#define LANG_FL_tVacation_uModDate "uModDate"
#define LANG_FT_tVacation_uModDate "Unix seconds date last update"
                                                                                  
