#!/bin/bash

#PURPOSE
#	Generate only the iptables nat table 
#	This script neds to be run only once per hardware node
#	No matter how many containers are configured at one time
#	to be NAT containers.
#	At this time everything is based upon NAT for asterisk/FreePBX.
#
#TODO
#	When system boots
#	/sbin/iptables-restore < /etc/sysconfig/iptables.natpbx2
#	must be run.

fLog() { echo "`date +%b' '%d' '%T` $0[$$]: $@" >> /tmp/ActivateNATNode.sh.log; }

if [ "$1" == "" ] ;then
	echo "usage: $0 <cSourceIPv4>";
	fLog "usage error";
	exit 1;
else
	cSourceIPv4="$1";
fi
fLog "start $1";

#iptables
#top part
cIptablesFile="/etc/sysconfig/iptables.natpbx2";
cat  > $cIptablesFile << EOF
#
# Generated by unxsVZ iptables_only.sample.sh
# 
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
#
EOF
#middle part. New unxsNATPBX adds SNAT rules also
/usr/sbin/unxsNATPBX CreateIptablesData $cSourceIPv4 >> $cIptablesFile;
#end part
cat  >> $cIptablesFile << EOF
#
COMMIT
# Generated by unxsVZ
EOF
echo "# `date +%b' '%d' '%T` $0[$$]: $@" >> $cIptablesFile
#uncomment to make this script do real work.
/sbin/iptables-restore < $cIptablesFile;
fLog "end";
