#!/bin/bash

if [ "$1" == "" ] ;then
	echo "usage: $0 <cSourceIPv4>";
	exit;
fi

function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

if ! valid_ip $1;then
	echo "Error: cSourceIPv4 $1 is not a valid dotted quad";
	exit 1;
fi

#iptables
#top part
cIptablesFile="/etc/sysconfig/iptables.natpbx2";
cat  > $cIptablesFile << EOF
# Generated by iptables-save v1.3.5 on Tue Apr 17 16:45:03 2012
*mangle
:PREROUTING ACCEPT [1811653:374879873]
:INPUT ACCEPT [63233:19133407]
:FORWARD ACCEPT [1748420:355746466]
:OUTPUT ACCEPT [66372:91163993]
:POSTROUTING ACCEPT [1814792:446910459]
COMMIT
# Completed on Tue Apr 17 16:45:03 2012
# Generated by iptables-save v1.3.5 on Tue Apr 17 16:45:03 2012
*nat
:PREROUTING ACCEPT [5817:543731]
:POSTROUTING ACCEPT [7538:667031]
:OUTPUT ACCEPT [1830:129241]
#
#
EOF
#middle part
/usr/sbin/unxsNATPBX CreateIptablesData $1 >> $cIptablesFile;
#end part
cat  >> $cIptablesFile << EOF
#
#for all pbx
-A POSTROUTING -s 10.0.4.0/255.255.255.0 -j SNAT --to-source $1
COMMIT
# Completed on Tue Apr 17 16:45:03 2012
# Generated by iptables-save v1.3.5 on Tue Apr 17 16:45:03 2012
*filter
:INPUT ACCEPT [63233:19133407]
:FORWARD ACCEPT [1748420:355746466]
:OUTPUT ACCEPT [66372:91163993]
COMMIT
# Completed on Tue Apr 17 16:45:03 2012
EOF

#iptables-restore < $cIptablesFile;

