#!/bin/bash

#PURPOSE
#	Generate only the iptables nat table 

fLog() { echo "`date +%b' '%d' '%T` $0[$$]: $@" >> /tmp/ActivateNATNodeContainer.sh.log; }

if [ "$2" == "" ] ;then
	echo "usage: $0 <uContainer> <cSourceIPv4>";
	fLog "usage error $0 $1 $2 $3";
	exit 1;
fi
fLog "start $1 $2 $3";

#iptables
#top part
cIptablesFile="/etc/sysconfig/iptables.natpbx2";
cat  > $cIptablesFile << EOF
#
# Generated by unxsVZ iptables_only.sample.sh
# 
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
#
EOF
#middle part. New unxsNATPBX adds SNAT rules also
/usr/sbin/unxsNATPBX CreateIptablesData $2 >> $cIptablesFile;
#end part
cat  >> $cIptablesFile << EOF
#
COMMIT
# Generated by unxsVZ
EOF
echo "# `date +%b' '%d' '%T` $0[$$]: $@" >> $cIptablesFile
#uncomment to make this script do real work.
/sbin/iptables-restore < $cIptablesFile;
fLog "end";
