#!/bin/bash
#FILE
#	getMailgraphImages.sh
#PURPOSE
#	This script should be used in crontab for getting the images
#	generated by the mailgraph.cgi script
#	With this we will access the mailgraph data
#	way faster either at the unxsMail or mail2Admin dashboards.
#
#AUTHOR
#	(C) 2008 Gary Wallis and Hugo Urquiza for Unixservice.
#	Gary Wallis, intelectual authorship ;)

URL="https://127.0.0.1/cgi-bin/mailgraph.cgi";
OUTPUT_DIR="/var/www/html/images";

rm -f $OUTPUT_DIR/mailgraph-lastday0.png;
wget --no-check-certificate -O $OUTPUT_DIR/mailgraph-lastday0.png -q $URL?0-n

rm -f $OUTPUT_DIR/mailgraph-lastday1.png;
wget --no-check-certificate -O $OUTPUT_DIR/mailgraph-lastday1.png -q $URL?0-e

rm -f $OUTPUT_DIR/mailgraph-lastweek0.png;
wget --no-check-certificate -O $OUTPUT_DIR/mailgraph-lastweek0.png -q $URL?1-n

rm -f $OUTPUT_DIR/mailgraph-lastweek1.png;
wget --no-check-certificate -O $OUTPUT_DIR/mailgraph-lastweek1.png -q $URL?1-n




