// svn ID removed
// Spanish: Argentina
// Navigation bar buttons and results

#define LANG_NB_LIST "Lista"
#define LANG_NB_MODIFY "Modificar"
#define LANG_NB_CONFIRMMOD "Confirmar Modificar"
#define LANG_NB_NEW "Nuevo"
#define LANG_NB_DELETE "Eliminar"
#define LANG_NB_CONFIRMNEW "Crear Nuevo"
#define LANG_NBB_CONFIRMNEW "<input title=\"Crear registro nuevo ahora\" class=lrevButton type=submit name=gcCommand value=\"Crear Nuevo\">"
#define LANG_NB_CONFIRMDEL "Confirmar Eliminar"
#define LANG_NBB_CONFIRMDEL "<input title=\"Eliminar registro ahora y para siempre\" class=lwarnButton type=submit name=gcCommand value=\"Confirmar Eliminar\">"
#define LANG_NBB_CONFIRMMOD "<input title=\"Modificar registro ahora\" class=lalertButton type=submit name=gcCommand value=\"Confirmar Modificar\">"

#define LANG_NBR_FOUND " Encontrado"
#define LANG_NBR_MODIFIED " Modificado"
#define LANG_NBR_NEW " Creado"
#define LANG_NBR_NORECS " No se encontro registro"
#define LANG_NBRF_SHOWING " (Mostrando %lu de %d)"

#define LANG_NBR_RECEXISTS "<blink>Registro ya existe"
#define LANG_NBR_NEWRECADDED "Nuevo registro %u creado"
#define LANG_NBR_RECDELETED "Registro eliminado"
#define LANG_NBR_RECNOTDELETED "Registro no eliminado: No existe"
#define LANG_NBR_RECNOTEXIST "<blink>Registro no existe"
#define LANG_NBR_MULTRECS "<blink>Multiples registros"
#define LANG_NBR_EXTMOD "<blink>Este registro acaba de ser modificado por otro usuario!"
#define LANG_NBRF_REC_MODIFIED "Registro %s modificado"

#define LANG_NBB_SKIPFIRST "<input title=\"Saltar al primero registro\" style='width:30px;' type=submit name=gcFind value=\"<<\" >"
#define LANG_NBB_SKIPBACK "<input title=\"Retroceder un registro\" style='width:30px;' type=submit name=gcFind value=\"< \" >"
#define LANG_NBB_SKIPNEXT "<input title=\"Avanzar al proximo registro\" style='width:30px;' type=submit name=gcFind value=\" >\" >"
#define LANG_NBB_SKIPLAST "<input title=\"Saltar al ultimo registro\" style='width:30px;' type=submit name=gcFind value=\">>\" >\n"


//Modifed for local .h use
#define LANG_NBB_NEWREV "<input title=\"Empezar a crear nuevo registro\" class=revButton type=submit name=gcCommand value=Nuevo>"
#define LANG_NBB_NEW "<input title=\"\" type=submit name=gcCommand value=Nuevo>"
#define LANG_NBB_DELETE "<input class=warnButton title=\"Comenzar a eliminar un registro\" type=submit name=gcCommand value=Eliminar>"
#define LANG_NBB_MODIFY "<input class=alertButton title=\"Comenzar a modificar registro\" type=submit name=gcCommand value=Modificar>"

#define LANG_NBB_LIST "<input title=\"Listado de registros paginado\" type=submit name=gcFind value=Lista>"
#define LANG_NBB_SEARCH "<input title=\"Buscar y cargar un registro\" class=revButton type=submit name=gcFind value=Buscar>"

#define LANG_PAGEMACHINE_HINT "No se encontro ningun registro.<br>"
#define LANG_PAGEMACHINE_SHOWING "Pagina %d/%d (Registros %d-%d de %d)\n"
#define LANG_PAGEMACHINE_SEARCH "<input class=revButton type=submit name=gcFind value=Buscar >"
#define LANG_PAGEMACHINE_SEARCHBUTTON "Buscar"

//tTemplate
#define LANG_FL_tTemplate_uTemplate "uTemplate"
#define LANG_FT_tTemplate_uTemplate "Primary Key"
#define LANG_FL_tTemplate_cLabel "cLabel"
#define LANG_FT_tTemplate_cLabel "Short label"
#define LANG_FL_tTemplate_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplate_uTemplateSet "Short label"
#define LANG_FL_tTemplate_uTemplateType "uTemplateType"
#define LANG_FT_tTemplate_uTemplateType "Short label"
#define LANG_FL_tTemplate_cComment "cComment"
#define LANG_FT_tTemplate_cComment "About the template"
#define LANG_FL_tTemplate_cTemplate "cTemplate"
#define LANG_FT_tTemplate_cTemplate "Template itself"
#define LANG_FL_tTemplate_uOwner "uOwner"
#define LANG_FT_tTemplate_uOwner "Record owner"
#define LANG_FL_tTemplate_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplate_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplate_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplate_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplate_uModBy "uModBy"
#define LANG_FT_tTemplate_uModBy "uClient for last update"
#define LANG_FL_tTemplate_uModDate "uModDate"
#define LANG_FT_tTemplate_uModDate "Unix seconds date last update"
//tTemplateSet
#define LANG_FL_tTemplateSet_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplateSet_uTemplateSet "Primary Key"
#define LANG_FL_tTemplateSet_cLabel "cLabel"
#define LANG_FT_tTemplateSet_cLabel "Short label"
#define LANG_FL_tTemplateSet_uOwner "uOwner"
#define LANG_FT_tTemplateSet_uOwner "Record owner"
#define LANG_FL_tTemplateSet_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateSet_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateSet_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateSet_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateSet_uModBy "uModBy"
#define LANG_FT_tTemplateSet_uModBy "uClient for last update"
#define LANG_FL_tTemplateSet_uModDate "uModDate"
#define LANG_FT_tTemplateSet_uModDate "Unix seconds date last update"
//tTemplateType
#define LANG_FL_tTemplateType_uTemplateType "uTemplateType"
#define LANG_FT_tTemplateType_uTemplateType "Primary Key"
#define LANG_FL_tTemplateType_cLabel "cLabel"
#define LANG_FT_tTemplateType_cLabel "Short label"
#define LANG_FL_tTemplateType_uOwner "uOwner"
#define LANG_FT_tTemplateType_uOwner "Record owner"
#define LANG_FL_tTemplateType_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateType_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateType_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateType_uModBy "uModBy"
#define LANG_FT_tTemplateType_uModBy "uClient for last update"
#define LANG_FL_tTemplateType_uModDate "uModDate"
#define LANG_FT_tTemplateType_uModDate "Unix seconds date last update"
//tConfiguration
#define LANG_FL_tConfiguration_uConfiguration "uConfiguration"
#define LANG_FT_tConfiguration_uConfiguration "Primary Key"
#define LANG_FL_tConfiguration_uServer "uServer"
#define LANG_FT_tConfiguration_uServer "uServer"
#define LANG_FL_tConfiguration_cLabel "cLabel"
#define LANG_FT_tConfiguration_cLabel "cLabel is Name of Name/Value Pair"
#define LANG_FL_tConfiguration_cValue "cValue"
#define LANG_FT_tConfiguration_cValue "Value of name(cLabel)/value pair"
#define LANG_FL_tConfiguration_cComment "cComment"
#define LANG_FT_tConfiguration_cComment "Comment about this configuration name/value pair"
#define LANG_FL_tConfiguration_uOwner "uOwner"
#define LANG_FT_tConfiguration_uOwner "Record owner"
#define LANG_FL_tConfiguration_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfiguration_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfiguration_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfiguration_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfiguration_uModBy "uModBy"
#define LANG_FT_tConfiguration_uModBy "uClient for last update"
#define LANG_FL_tConfiguration_uModDate "uModDate"
#define LANG_FT_tConfiguration_uModDate "Unix seconds date last update"
//tLog
#define LANG_FL_tLog_uLog "uLog"
#define LANG_FT_tLog_uLog "Primary Key"
#define LANG_FL_tLog_cLabel "cLabel"
#define LANG_FT_tLog_cLabel "Short label"
#define LANG_FL_tLog_uLogType "uLogType"
#define LANG_FT_tLog_uLogType "Log Type"
#define LANG_FL_tLog_cHash "cHash"
#define LANG_FT_tLog_cHash "Security hash to complicate tampering"
#define LANG_FL_tLog_uPermLevel "uPermLevel"
#define LANG_FT_tLog_uPermLevel "User Perm Level"
#define LANG_FL_tLog_uLoginClient "uLoginClient"
#define LANG_FT_tLog_uLoginClient "Client Number"
#define LANG_FL_tLog_cLogin "cLogin"
#define LANG_FT_tLog_cLogin "Login name"
#define LANG_FL_tLog_cHost "cHost"
#define LANG_FT_tLog_cHost "Ip Address"
#define LANG_FL_tLog_uTablePK "uTablePK"
#define LANG_FT_tLog_uTablePK "Primar Key of the Table"
#define LANG_FL_tLog_cTableName "cTableName"
#define LANG_FT_tLog_cTableName "Name of the Table"
#define LANG_FL_tLog_cMessage "cMessage"
#define LANG_FT_tLog_cMessage "Message text"
#define LANG_FL_tLog_cServer "cServer"
#define LANG_FT_tLog_cServer "Server name"
#define LANG_FL_tLog_uOwner "uOwner"
#define LANG_FT_tLog_uOwner "Record owner"
#define LANG_FL_tLog_uCreatedBy "uCreatedBy"
#define LANG_FT_tLog_uCreatedBy "uClient for last insert"
#define LANG_FL_tLog_uCreatedDate "uCreatedDate"
#define LANG_FT_tLog_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLog_uModBy "uModBy"
#define LANG_FT_tLog_uModBy "uClient for last update"
#define LANG_FL_tLog_uModDate "uModDate"
#define LANG_FT_tLog_uModDate "Unix seconds date last update"
//tLogType
#define LANG_FL_tLogType_uLogType "uLogType"
#define LANG_FT_tLogType_uLogType "Primary Key"
#define LANG_FL_tLogType_cLabel "cLabel"
#define LANG_FT_tLogType_cLabel "Short label"
#define LANG_FL_tLogType_uOwner "uOwner"
#define LANG_FT_tLogType_uOwner "Record owner"
#define LANG_FL_tLogType_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogType_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogType_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogType_uModBy "uModBy"
#define LANG_FT_tLogType_uModBy "uClient for last update"
#define LANG_FL_tLogType_uModDate "uModDate"
#define LANG_FT_tLogType_uModDate "Unix seconds date last update"
//tLogMonth
#define LANG_FL_tLogMonth_uLog "uLog"
#define LANG_FT_tLogMonth_uLog "Primary Key"
#define LANG_FL_tLogMonth_cLabel "cLabel"
#define LANG_FT_tLogMonth_cLabel "Short label"
#define LANG_FL_tLogMonth_uLogType "uLogType"
#define LANG_FT_tLogMonth_uLogType "Log Type"
#define LANG_FL_tLogMonth_cHash "cHash"
#define LANG_FT_tLogMonth_cHash "Security hash to complicate tampering"
#define LANG_FL_tLogMonth_uPermLevel "uPermLevel"
#define LANG_FT_tLogMonth_uPermLevel "User Perm Level"
#define LANG_FL_tLogMonth_uLoginClient "uLoginClient"
#define LANG_FT_tLogMonth_uLoginClient "Client Number"
#define LANG_FL_tLogMonth_cLogin "cLogin"
#define LANG_FT_tLogMonth_cLogin "Login name"
#define LANG_FL_tLogMonth_cHost "cHost"
#define LANG_FT_tLogMonth_cHost "Ip Address"
#define LANG_FL_tLogMonth_uTablePK "uTablePK"
#define LANG_FT_tLogMonth_uTablePK "Primar Key of the Table"
#define LANG_FL_tLogMonth_cTableName "cTableName"
#define LANG_FT_tLogMonth_cTableName "Name of the Table"
#define LANG_FL_tLogMonth_uOwner "uOwner"
#define LANG_FT_tLogMonth_uOwner "Record owner"
#define LANG_FL_tLogMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogMonth_uModBy "uModBy"
#define LANG_FT_tLogMonth_uModBy "uClient for last update"
#define LANG_FL_tLogMonth_uModDate "uModDate"
#define LANG_FT_tLogMonth_uModDate "Unix seconds date last update"
//tClient
#define LANG_FL_tClient_uClient "uClient"
#define LANG_FT_tClient_uClient "Primary Key"
#define LANG_FL_tClient_cLabel "cLabel"
#define LANG_FT_tClient_cLabel "Short label"
#define LANG_FL_tClient_cInfo "cInfo"
#define LANG_FT_tClient_cInfo "Unformatted info/address etc."
#define LANG_FL_tClient_cEmail "cEmail"
#define LANG_FT_tClient_cEmail "Main Email"
#define LANG_FL_tClient_cCode "cCode"
#define LANG_FT_tClient_cCode "Enterprise wide customer/contact tracking"
#define LANG_FL_tClient_uOwner "uOwner"
#define LANG_FT_tClient_uOwner "Record owner"
#define LANG_FL_tClient_uCreatedBy "uCreatedBy"
#define LANG_FT_tClient_uCreatedBy "uClient for last insert"
#define LANG_FL_tClient_uCreatedDate "uCreatedDate"
#define LANG_FT_tClient_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tClient_uModBy "uModBy"
#define LANG_FT_tClient_uModBy "uClient for last update"
#define LANG_FL_tClient_uModDate "uModDate"
#define LANG_FT_tClient_uModDate "Unix seconds date last update"
//tAuthorize
#define LANG_FL_tAuthorize_uAuthorize "uAuthorize"
#define LANG_FT_tAuthorize_uAuthorize "Primary Key"
#define LANG_FL_tAuthorize_cLabel "cLabel"
#define LANG_FT_tAuthorize_cLabel "Short label"
#define LANG_FL_tAuthorize_cIpMask "cIpMask"
#define LANG_FT_tAuthorize_cIpMask "Allow user from this IP"
#define LANG_FL_tAuthorize_uPerm "uPerm"
#define LANG_FT_tAuthorize_uPerm "User permission level"
#define LANG_FL_tAuthorize_uCertClient "uCertClient"
#define LANG_FT_tAuthorize_uCertClient "User uClient"
#define LANG_FL_tAuthorize_cPasswd "cPasswd"
#define LANG_FT_tAuthorize_cPasswd "Encrypted cgi login password"
#define LANG_FL_tAuthorize_cClrPasswd "cClrPasswd"
#define LANG_FT_tAuthorize_cClrPasswd "Optionally used non encrypted login password"
#define LANG_FL_tAuthorize_uOwner "uOwner"
#define LANG_FT_tAuthorize_uOwner "Record owner"
#define LANG_FL_tAuthorize_uCreatedBy "uCreatedBy"
#define LANG_FT_tAuthorize_uCreatedBy "uClient for last insert"
#define LANG_FL_tAuthorize_uCreatedDate "uCreatedDate"
#define LANG_FT_tAuthorize_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tAuthorize_uModBy "uModBy"
#define LANG_FT_tAuthorize_uModBy "uClient for last update"
#define LANG_FL_tAuthorize_uModDate "uModDate"
#define LANG_FT_tAuthorize_uModDate "Unix seconds date last update"
//tMonth
#define LANG_FL_tMonth_uMonth "uMonth"
#define LANG_FT_tMonth_uMonth "Primary Key"
#define LANG_FL_tMonth_cLabel "cLabel"
#define LANG_FT_tMonth_cLabel "Name of Archive Table Ex. tNov2009"
#define LANG_FL_tMonth_uOwner "uOwner"
#define LANG_FT_tMonth_uOwner "Record owner"
#define LANG_FL_tMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tMonth_uModBy "uModBy"
#define LANG_FT_tMonth_uModBy "uClient for last update"
#define LANG_FL_tMonth_uModDate "uModDate"
#define LANG_FT_tMonth_uModDate "Unix seconds date last update"
//tGlossary
#define LANG_FL_tGlossary_uGlossary "uGlossary"
#define LANG_FT_tGlossary_uGlossary "Primary Key"
#define LANG_FL_tGlossary_cLabel "cLabel"
#define LANG_FT_tGlossary_cLabel "Short label"
#define LANG_FL_tGlossary_cText "cText"
#define LANG_FT_tGlossary_cText "Definition of the label referenced in cLabel"
#define LANG_FL_tGlossary_uOwner "uOwner"
#define LANG_FT_tGlossary_uOwner "Record owner"
#define LANG_FL_tGlossary_uCreatedBy "uCreatedBy"
#define LANG_FT_tGlossary_uCreatedBy "uClient for last insert"
#define LANG_FL_tGlossary_uCreatedDate "uCreatedDate"
#define LANG_FT_tGlossary_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGlossary_uModBy "uModBy"
#define LANG_FT_tGlossary_uModBy "uClient for last update"
#define LANG_FL_tGlossary_uModDate "uModDate"
#define LANG_FT_tGlossary_uModDate "Unix seconds date last update"
//tJob
#define LANG_FL_tJob_uJob "uJob"
#define LANG_FT_tJob_uJob "Primary Key"
#define LANG_FL_tJob_cLabel "cLabel"
#define LANG_FT_tJob_cLabel "Label for user feedback"
#define LANG_FL_tJob_cServer "cServer"
#define LANG_FT_tJob_cServer "Server name ip or any server"
#define LANG_FL_tJob_cJobName "cJobName"
#define LANG_FT_tJob_cJobName "Subsystem.Function style job name"
#define LANG_FL_tJob_uJobTarget "uJobTarget"
#define LANG_FT_tJob_uJobTarget "Owner of resources created/mod"
#define LANG_FL_tJob_uJobTargetUser "uJobTargetUser"
#define LANG_FT_tJob_uJobTargetUser "Target User ID"
#define LANG_FL_tJob_cJobData "cJobData"
#define LANG_FT_tJob_cJobData "Remote subsystem server function arguments"
#define LANG_FL_tJob_uJobDate "uJobDate"
#define LANG_FT_tJob_uJobDate "Unix seconds for job to start to be considered"
#define LANG_FL_tJob_uJobStatus "uJobStatus"
#define LANG_FT_tJob_uJobStatus "Waiting, being processed, done, error"
#define LANG_FL_tJob_cRemoteMsg "cRemoteMsg"
#define LANG_FT_tJob_cRemoteMsg "Remote subsytem error message"
#define LANG_FL_tJob_uOwner "uOwner"
#define LANG_FT_tJob_uOwner "Record owner"
#define LANG_FL_tJob_uCreatedBy "uCreatedBy"
#define LANG_FT_tJob_uCreatedBy "uClient for last insert"
#define LANG_FL_tJob_uCreatedDate "uCreatedDate"
#define LANG_FT_tJob_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJob_uModBy "uModBy"
#define LANG_FT_tJob_uModBy "uClient for last update"
#define LANG_FL_tJob_uModDate "uModDate"
#define LANG_FT_tJob_uModDate "Unix seconds date last update"
//tServer
#define LANG_FL_tServer_uServer "uServer"
#define LANG_FT_tServer_uServer "Primary Key"
#define LANG_FL_tServer_cLabel "cLabel"
#define LANG_FT_tServer_cLabel "Short label"
#define LANG_FL_tServer_uOwner "uOwner"
#define LANG_FT_tServer_uOwner "Record owner"
#define LANG_FL_tServer_uCreatedBy "uCreatedBy"
#define LANG_FT_tServer_uCreatedBy "uClient for last insert"
#define LANG_FL_tServer_uCreatedDate "uCreatedDate"
#define LANG_FT_tServer_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tServer_uModBy "uModBy"
#define LANG_FT_tServer_uModBy "uClient for last update"
#define LANG_FL_tServer_uModDate "uModDate"
#define LANG_FT_tServer_uModDate "Unix seconds date last update"
//tJobStatus
#define LANG_FL_tJobStatus_uJobStatus "uJobStatus"
#define LANG_FT_tJobStatus_uJobStatus "Primary Key"
#define LANG_FL_tJobStatus_cLabel "cLabel"
#define LANG_FT_tJobStatus_cLabel "Short label"
#define LANG_FL_tJobStatus_uOwner "uOwner"
#define LANG_FT_tJobStatus_uOwner "Record owner"
#define LANG_FL_tJobStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tJobStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tJobStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tJobStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJobStatus_uModBy "uModBy"
#define LANG_FT_tJobStatus_uModBy "uClient for last update"
#define LANG_FL_tJobStatus_uModDate "uModDate"
#define LANG_FT_tJobStatus_uModDate "Unix seconds date last update"
//tStatus
#define LANG_FL_tStatus_uStatus "uStatus"
#define LANG_FT_tStatus_uStatus "Primary Key"
#define LANG_FL_tStatus_cLabel "cLabel"
#define LANG_FT_tStatus_cLabel "Short label"
#define LANG_FL_tStatus_uOwner "uOwner"
#define LANG_FT_tStatus_uOwner "Record owner"
#define LANG_FL_tStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tStatus_uModBy "uModBy"
#define LANG_FT_tStatus_uModBy "uClient for last update"
#define LANG_FL_tStatus_uModDate "uModDate"
#define LANG_FT_tStatus_uModDate "Unix seconds date last update"
//tRadacct
#define LANG_FL_tRadacct_uRadacct "uRadacct"
#define LANG_FT_tRadacct_uRadacct "Primary key for interface use only"
#define LANG_FL_tRadacct_cLogin "cLogin"
#define LANG_FT_tRadacct_cLogin "Login name"
#define LANG_FL_tRadacct_cSessionID "cSessionID"
#define LANG_FT_tRadacct_cSessionID "Radius session ID"
#define LANG_FL_tRadacct_cNAS "cNAS"
#define LANG_FT_tRadacct_cNAS "NAS server IP"
#define LANG_FL_tRadacct_uConnectTime "uConnectTime"
#define LANG_FT_tRadacct_uConnectTime "Seconds from stop record"
#define LANG_FL_tRadacct_uPort "uPort"
#define LANG_FT_tRadacct_uPort "NAS port used during session"
#define LANG_FL_tRadacct_uPortType "uPortType"
#define LANG_FT_tRadacct_uPortType "NAS port_type"
#define LANG_FL_tRadacct_uService "uService"
#define LANG_FT_tRadacct_uService "Service type PPP/Telnet/Etc"
#define LANG_FL_tRadacct_uProtocol "uProtocol"
#define LANG_FT_tRadacct_uProtocol "Session Protocol"
#define LANG_FL_tRadacct_cIP "cIP"
#define LANG_FT_tRadacct_cIP "IP assigned"
#define LANG_FL_tRadacct_cLine "cLine"
#define LANG_FT_tRadacct_cLine "PoP number called"
#define LANG_FL_tRadacct_cCallerID "cCallerID"
#define LANG_FT_tRadacct_cCallerID "Caller ID"
#define LANG_FL_tRadacct_uInBytes "uInBytes"
#define LANG_FT_tRadacct_uInBytes "Bytes from user"
#define LANG_FL_tRadacct_uOutBytes "uOutBytes"
#define LANG_FT_tRadacct_uOutBytes "Bytes to user"
#define LANG_FL_tRadacct_uTermCause "uTermCause"
#define LANG_FT_tRadacct_uTermCause "Termination cause code"
#define LANG_FL_tRadacct_uStartTime "uStartTime"
#define LANG_FT_tRadacct_uStartTime "Start record timestamp"
#define LANG_FL_tRadacct_uStopTime "uStopTime"
#define LANG_FT_tRadacct_uStopTime "Stop record timestamp"
#define LANG_FL_tRadacct_cInfo "cInfo"
#define LANG_FT_tRadacct_cInfo "Connect info"
//tMonth
#define LANG_FL_tMonth_uMonth "uMonth"
#define LANG_FT_tMonth_uMonth "Primary Key"
#define LANG_FL_tMonth_cLabel "cLabel"
#define LANG_FT_tMonth_cLabel "Short label"
#define LANG_FL_tMonth_uOwner "uOwner"
#define LANG_FT_tMonth_uOwner "Record owner"
#define LANG_FL_tMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tMonth_uModBy "uModBy"
#define LANG_FT_tMonth_uModBy "uClient for last update"
#define LANG_FL_tMonth_uModDate "uModDate"
#define LANG_FT_tMonth_uModDate "Unix seconds date last update"
//tRadacctMonth
#define LANG_FL_tRadacctMonth_uRadacct "uRadacct"
#define LANG_FT_tRadacctMonth_uRadacct "Primary key for interface use only"
#define LANG_FL_tRadacctMonth_cLogin "cLogin"
#define LANG_FT_tRadacctMonth_cLogin "Login name"
#define LANG_FL_tRadacctMonth_cSessionID "cSessionID"
#define LANG_FT_tRadacctMonth_cSessionID "Radius session ID"
#define LANG_FL_tRadacctMonth_cNAS "cNAS"
#define LANG_FT_tRadacctMonth_cNAS "NAS server IP"
#define LANG_FL_tRadacctMonth_uConnectTime "uConnectTime"
#define LANG_FT_tRadacctMonth_uConnectTime "Seconds from stop record"
#define LANG_FL_tRadacctMonth_uPort "uPort"
#define LANG_FT_tRadacctMonth_uPort "NAS port used during session"
#define LANG_FL_tRadacctMonth_uPortType "uPortType"
#define LANG_FT_tRadacctMonth_uPortType "NAS port_type"
#define LANG_FL_tRadacctMonth_uService "uService"
#define LANG_FT_tRadacctMonth_uService "Service type PPP/Telnet/Etc"
#define LANG_FL_tRadacctMonth_uProtocol "uProtocol"
#define LANG_FT_tRadacctMonth_uProtocol "Session Protocol"
#define LANG_FL_tRadacctMonth_cIP "cIP"
#define LANG_FT_tRadacctMonth_cIP "IP assigned"
#define LANG_FL_tRadacctMonth_cLine "cLine"
#define LANG_FT_tRadacctMonth_cLine "PoP number called"
#define LANG_FL_tRadacctMonth_cCallerID "cCallerID"
#define LANG_FT_tRadacctMonth_cCallerID "Caller ID"
#define LANG_FL_tRadacctMonth_uInBytes "uInBytes"
#define LANG_FT_tRadacctMonth_uInBytes "Bytes from user"
#define LANG_FL_tRadacctMonth_uOutBytes "uOutBytes"
#define LANG_FT_tRadacctMonth_uOutBytes "Bytes to user"
#define LANG_FL_tRadacctMonth_uTermCause "uTermCause"
#define LANG_FT_tRadacctMonth_uTermCause "Termination cause code"
#define LANG_FL_tRadacctMonth_uStartTime "uStartTime"
#define LANG_FT_tRadacctMonth_uStartTime "Start record timestamp"
#define LANG_FL_tRadacctMonth_uStopTime "uStopTime"
#define LANG_FT_tRadacctMonth_uStopTime "Stop record timestamp"
#define LANG_FL_tRadacctMonth_cInfo "cInfo"
#define LANG_FT_tRadacctMonth_cInfo "Connect info"
//tConfiguration
#define LANG_FL_tConfiguration_uConfiguration "uConfiguration"
#define LANG_FT_tConfiguration_uConfiguration "Primary Key"
#define LANG_FL_tConfiguration_cLabel "cLabel"
#define LANG_FT_tConfiguration_cLabel "Short label"
#define LANG_FL_tConfiguration_cValue "cValue"
#define LANG_FT_tConfiguration_cValue "Value of name(cLabel)/value pair"
#define LANG_FL_tConfiguration_cComment "cValue"
#define LANG_FT_tConfiguration_cComment "Comment about this configuration name/value pair"
#define LANG_FL_tConfiguration_uOwner "uOwner"
#define LANG_FT_tConfiguration_uOwner "Record owner"
#define LANG_FL_tConfiguration_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfiguration_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfiguration_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfiguration_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfiguration_uModBy "uModBy"
#define LANG_FT_tConfiguration_uModBy "uClient for last update"
#define LANG_FL_tConfiguration_uModDate "uModDate"
#define LANG_FT_tConfiguration_uModDate "Unix seconds date last update"
//tAuthorize
#define LANG_FL_tAuthorize_uAuthorize "uAuthorize"
#define LANG_FT_tAuthorize_uAuthorize "Primary Key"
#define LANG_FL_tAuthorize_cLabel "cLabel"
#define LANG_FT_tAuthorize_cLabel "Short label"
#define LANG_FL_tAuthorize_cIpMask "cIpMask"
#define LANG_FT_tAuthorize_cIpMask "Allow user from this IP"
#define LANG_FL_tAuthorize_uPerm "uPerm"
#define LANG_FT_tAuthorize_uPerm "User permission level"
#define LANG_FL_tAuthorize_uCertClient "uCertClient"
#define LANG_FT_tAuthorize_uCertClient "User uClient"
#define LANG_FL_tAuthorize_cPasswd "cPasswd"
#define LANG_FT_tAuthorize_cPasswd "Unix crypt() password"
#define LANG_FL_tAuthorize_uOwner "uOwner"
#define LANG_FT_tAuthorize_uOwner "Record owner"
#define LANG_FL_tAuthorize_uCreatedBy "uCreatedBy"
#define LANG_FT_tAuthorize_uCreatedBy "uClient for last insert"
#define LANG_FL_tAuthorize_uCreatedDate "uCreatedDate"
#define LANG_FT_tAuthorize_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tAuthorize_uModBy "uModBy"
#define LANG_FT_tAuthorize_uModBy "uClient for last update"
#define LANG_FL_tAuthorize_uModDate "uModDate"
#define LANG_FT_tAuthorize_uModDate "Unix seconds date last update"
//tClient
#define LANG_FL_tClient_uClient "uClient"
#define LANG_FT_tClient_uClient "Primary Key"
#define LANG_FL_tClient_cLabel "cLabel"
#define LANG_FT_tClient_cLabel "Short label"
#define LANG_FL_tClient_uOwner "uOwner"
#define LANG_FT_tClient_uOwner "Record owner"
#define LANG_FL_tClient_uCreatedBy "uCreatedBy"
#define LANG_FT_tClient_uCreatedBy "uClient for last insert"
#define LANG_FL_tClient_uCreatedDate "uCreatedDate"
#define LANG_FT_tClient_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tClient_uModBy "uModBy"
#define LANG_FT_tClient_uModBy "uClient for last update"
#define LANG_FL_tClient_uModDate "uModDate"
#define LANG_FT_tClient_uModDate "Unix seconds date last update"
