#!/bin/sh
#
# This script will be executed *after* all the other init scripts.
# You can put your own initialization stuff in here if you don't
# want to do the full Sys V style init stuff.

touch /var/lock/subsys/local

#
#Unixservice ggw 11/2006 - 5/2007
#
/etc/init.d/mysqld start;
sleep 1;
/usr/sbin/idns-logquery;
/usr/local/sbin/named -u named -c /usr/local/idns/named.conf;
